import type { AppSettings } from "./settings";
import type { ModelCapabilities, RuntimeStatus } from "./server";


/**
 * Phase 2.8: rendering hint for tool-call output. Tools that opt in
 * to structured output set this on their result so the UI knows
 * whether to render a table, code block, markdown body, image, or a
 * chart. Tools that don't override `execute_structured` send `null`
 * and the frontend falls back to the legacy collapsible-JSON view.
 */
export type ToolRenderAs = "table" | "code" | "markdown" | "image" | "chart" | "json";

export interface ToolCallInfo {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  result: string;
  elapsed: number;
  /** Phase 2.8: rendering hint. Null/undefined → JSON fallback. */
  renderAs?: ToolRenderAs | null;
  /** Phase 2.8: structured payload matching the renderAs shape. */
  data?: Record<string, unknown> | null;
}

export interface CitationInfo {
  docId: string;
  docName: string;
  chunkIndex: number;
  page?: number | null;
  preview: string;
}

export type ChatStreamPhase = "prompt_eval" | "generating";

/**
 * Phase 2.5: one alternate response generated by a different model
 * for the same prompt. Stored on the assistant message it siblings
 * so the chat thread can render primary + variants together.
 */
export interface ChatMessageVariant {
  modelRef: string;
  modelName: string;
  text: string;
  reasoning?: string | null;
  // Forward declare to avoid a circular ../types import; the consumer of
  // this field always has the full GenerationMetrics shape on hand.
  metrics?: import("../types").GenerationMetrics | null;
  generatedAt?: string;
}

/**
 * Phase 3.3: per-token logprob entry. Mirrors the OpenAI-spec
 * `logprobs.content[]` shape. Top-k alternatives let the hover
 * popover show what the model nearly said instead.
 */
export interface TokenLogprob {
  token: string | null;
  logprob: number | null;
  alternatives: Array<{ token: string | null; logprob: number | null }>;
}

export interface ChatPanicSignal {
  /** User-visible panic message from the backend. */
  message: string;
  /** Available RAM (GB) sampled at panic emission. */
  availableGb?: number;
  /** Combined memory pressure percentage at panic emission. */
  pressurePercent?: number;
}

export interface ChatThermalWarning {
  /** Reported thermal state from backend ("moderate" | "critical"). */
  state: "moderate" | "critical";
  /** User-visible thermal message from backend. */
  message: string;
}

export interface ChatMessage {
  role: "user" | "assistant";
  text: string;
  images?: string[];
  reasoning?: string;
  reasoningDone?: boolean | null;
  metrics?: import("../types").GenerationMetrics | null;
  toolCalls?: ToolCallInfo[];
  citations?: CitationInfo[];
  /**
   * Live phase tracker for the streaming assistant message (Phase 2.0).
   * Cleared once the message finalises via the backend's done event. Used
   * to render an explicit prompt-processing indicator before the first
   * token arrives instead of a blank flashing cursor.
   */
  streamPhase?: ChatStreamPhase | null;
  /**
   * Phase 2.0.5-G: panic signal emitted mid-stream when system memory
   * crosses critical thresholds. Renders a non-blocking warning banner
   * so the user can decide whether to cancel before the host wedges.
   */
  panic?: ChatPanicSignal | null;
  /**
   * Phase 2.0.5-I: thermal pressure warning emitted mid-stream when
   * the host is throttling. Renders a non-blocking warning banner.
   */
  thermalWarning?: ChatThermalWarning | null;
  /** Phase 2.5: alternate responses from other models for the same prompt. */
  variants?: ChatMessageVariant[];
  /**
   * Phase 3.3: cumulative per-token logprobs captured during streaming
   * when the request had `logprobs: N` set. Only populated for
   * llama-server; MLX worker passthrough is a follow-up.
   */
  tokenLogprobs?: TokenLogprob[];
}

export interface SessionDocument {
  id: string;
  filename: string;
  originalName: string;
  sizeBytes: number;
  chunkCount: number;
  uploadedAt: string;
}

export type ChatThinkingMode = "off" | "auto";
export type ChatReasoningEffort = "low" | "medium" | "high";

export interface ChatSession {
  id: string;
  title: string;
  documents?: SessionDocument[];
  updatedAt: string;
  pinned?: boolean;
  model: string;
  modelRef?: string | null;
  canonicalRepo?: string | null;
  modelSource?: string | null;
  modelPath?: string | null;
  modelBackend?: string | null;
  thinkingMode?: ChatThinkingMode | null;
  reasoningEffort?: ChatReasoningEffort | null;
  cacheLabel: string;
  cacheStrategy?: string | null;
  cacheBits?: number | null;
  fp16Layers?: number | null;
  fusedAttention?: boolean | null;
  fitModelInMemory?: boolean | null;
  contextTokens?: number | null;
  speculativeDecoding?: boolean | null;
  dflashDraftModel?: string | null;
  treeBudget?: number | null;
  /**
   * Phase 2.4: when this session was forked from another, the source
   * session's id. Sidebar reads this to render a fork-relationship
   * hint and the future merge/diff features key off it.
   */
  parentSessionId?: string | null;
  /** Phase 2.4: index of the last message copied from the parent. */
  forkedAtMessageIndex?: number | null;
  messages: ChatMessage[];
}

export interface CreateSessionResponse {
  session: ChatSession;
}

export interface UpdateSessionPayload {
  title?: string;
  model?: string | null;
  modelRef?: string | null;
  canonicalRepo?: string | null;
  modelSource?: string | null;
  modelPath?: string | null;
  modelBackend?: string | null;
  thinkingMode?: ChatThinkingMode | null;
  reasoningEffort?: ChatReasoningEffort | null;
  pinned?: boolean | null;
  cacheStrategy?: string | null;
  cacheBits?: number | null;
  fp16Layers?: number | null;
  fusedAttention?: boolean | null;
  fitModelInMemory?: boolean | null;
  contextTokens?: number | null;
  speculativeDecoding?: boolean | null;
  dflashDraftModel?: string | null;
  treeBudget?: number | null;
  messages?: ChatMessage[];
}

export interface GeneratePayload {
  sessionId?: string;
  title?: string;
  prompt: string;
  images?: string[];
  modelRef?: string;
  modelName?: string;
  canonicalRepo?: string;
  source?: string;
  path?: string;
  backend?: string;
  thinkingMode?: ChatThinkingMode;
  reasoningEffort?: ChatReasoningEffort;
  systemPrompt?: string;
  temperature?: number;
  maxTokens?: number;
  // Phase 2.2: full sampler chain. None means "use backend default".
  // llama-server applies all of these natively; mlx-lm uses what its
  // make_sampler signature supports (top_p, top_k, min_p) and silently
  // ignores the rest.
  topP?: number;
  topK?: number;
  minP?: number;
  repeatPenalty?: number;
  seed?: number;
  mirostatMode?: 0 | 1 | 2;
  mirostatTau?: number;
  mirostatEta?: number;
  // Modern anti-repetition / variety samplers (tier 2). llama-server
  // applies all; mlx-lm applies XTC via make_sampler and ignores DRY.
  xtcProbability?: number;
  xtcThreshold?: number;
  dryMultiplier?: number;
  jsonSchema?: Record<string, unknown>;
  /**
   * Phase 3.3: when set, asks llama-server to return top-k logprobs
   * per token. Bandwidth cost is non-trivial — gate via the advanced
   * mode setting, not a per-turn chip.
   */
  logprobs?: number;
  cacheBits?: number;
  fp16Layers?: number;
  fusedAttention?: boolean;
  cacheStrategy?: string;
  fitModelInMemory?: boolean;
  contextTokens?: number;
  speculativeDecoding?: boolean;
  // Agent tool-use
  enableTools?: boolean;
  availableTools?: string[];
  /**
   * Phase 2.12: when true, the model selectors in this payload override
   * the loaded runtime for THIS turn only — the session's stored
   * `modelRef` / `model` / `modelSource` etc. are not updated, so the
   * thread reverts to its default model on the next plain message.
   */
  oneTurnOverride?: boolean;
}

/**
 * Phase 2.2: per-thread sampler override blob. Stored in localStorage
 * keyed by session id. useChat reads it when assembling stream payloads;
 * the SamplerPanel writes it back when the user adjusts a slider.
 */
export interface SamplerOverrides {
  topP?: number | null;
  topK?: number | null;
  minP?: number | null;
  repeatPenalty?: number | null;
  seed?: number | null;
  mirostatMode?: 0 | 1 | 2 | null;
  mirostatTau?: number | null;
  mirostatEta?: number | null;
  xtcProbability?: number | null;
  xtcThreshold?: number | null;
  dryMultiplier?: number | null;
  /**
   * Phase 2.2: opt-in constrained decoding. Raw JSON-schema text the
   * user typed in the SamplerPanel. Parsed at send-time and forwarded
   * as `jsonSchema` on the GenerateRequest. Stored as raw text rather
   * than a parsed object so we can round-trip user edits even when
   * the schema is mid-type and not valid JSON yet.
   */
  jsonSchemaText?: string | null;
}

export interface GenerateResponse {
  session: ChatSession;
  assistant: ChatMessage;
  runtime: RuntimeStatus;
}


// ---------------------------------------------------------------------------
// UI-helper types — not API payload shapes, kept here so the chat domain
// owns its complete vocabulary (server payload + UI representation).
// ---------------------------------------------------------------------------

export interface ChatModelOption {
  key: string;
  label: string;
  detail: string;
  group: string;
  model: string;
  modelRef: string;
  canonicalRepo?: string | null;
  source: string;
  path?: string | null;
  backend: string;
  paramsB?: number;
  sizeGb?: number;
  contextWindow?: string;
  format?: string;
  quantization?: string;
  maxContext?: number | null;
  /** Phase 2.11: typed capabilities resolved from catalog tags + ref. */
  capabilities?: ModelCapabilities | null;
}

export interface DataDirRestartPrompt {
  migration: {
    copied: string[];
    skipped: string[];
    from: string;
    to: string;
  } | null;
}

export type SettingsDraft = {
  modelDirectories: AppSettings["modelDirectories"];
  preferredServerPort: number;
  allowRemoteConnections: boolean;
  requireApiAuth: boolean;
  autoStartServer: boolean;
  remoteProviders: AppSettings["remoteProviders"];
  huggingFaceToken: string;
  hasHuggingFaceToken: boolean;
  huggingFaceTokenMasked: string;
  dataDirectory: string;
  imageOutputsDirectory: string;
  videoOutputsDirectory: string;
  // FU-042 — persisted UI locale. ``"system"`` (default) auto-detects.
  locale: string;
  // FU-042 — clock format override. ``"system"`` honours locale default.
  clockFormat: "system" | "12h" | "24h";
};
