from __future__ import annotations

from typing import Any


IMAGE_MODEL_FAMILIES: list[dict[str, Any]] = [
    {
        "id": "flux-fast",
        "name": "FLUX.1 Schnell",
        "provider": "Black Forest Labs",
        "headline": "Fast prompt-to-image path for quick concepting and moodboards.",
        "summary": "Best starter option for rapid local ideation when you care more about speed and iteration than maximum fidelity.",
        "updatedLabel": "Curated starter pick",
        "badges": ["Fast", "General", "Photoreal"],
        "defaultVariantId": "black-forest-labs/FLUX.1-schnell",
        "variants": [
            {
                "id": "black-forest-labs/FLUX.1-schnell",
                "familyId": "flux-fast",
                "name": "FLUX.1 Schnell",
                "provider": "Black Forest Labs",
                "repo": "black-forest-labs/FLUX.1-schnell",
                "link": "https://huggingface.co/black-forest-labs/FLUX.1-schnell",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["photoreal", "general", "fast"],
                "taskSupport": ["txt2img"],
                "sizeGb": 23.7,
                "recommendedResolution": "1024x1024",
                "note": "Fastest concepting option in the curated image catalog.",
                "estimatedGenerationSeconds": 4.2,
                "releaseDate": "2024-08",
            },
            {
                "id": "black-forest-labs/FLUX.1-schnell-gguf-q4km",
                "familyId": "flux-fast",
                "name": "FLUX.1 Schnell · GGUF Q4_K_M",
                "provider": "Black Forest Labs · city96",
                "repo": "black-forest-labs/FLUX.1-schnell",
                "ggufRepo": "city96/FLUX.1-schnell-gguf",
                "ggufFile": "flux1-schnell-Q4_K_M.gguf",
                "link": "https://huggingface.co/city96/FLUX.1-schnell-gguf",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["photoreal", "general", "fast", "gguf"],
                "taskSupport": ["txt2img"],
                "sizeGb": 6.8,
                "recommendedResolution": "1024x1024",
                "note": "GGUF Q4_K_M — quantizes the FLUX transformer; the full diffusers pipeline still carries the base text encoders/VAE in memory.",
                "estimatedGenerationSeconds": 5.2,
                "releaseDate": "2024-09",
            },
            {
                "id": "black-forest-labs/FLUX.1-schnell-gguf-q8",
                "familyId": "flux-fast",
                "name": "FLUX.1 Schnell · GGUF Q8_0",
                "provider": "Black Forest Labs · city96",
                "repo": "black-forest-labs/FLUX.1-schnell",
                "ggufRepo": "city96/FLUX.1-schnell-gguf",
                "ggufFile": "flux1-schnell-Q8_0.gguf",
                "link": "https://huggingface.co/city96/FLUX.1-schnell-gguf",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["photoreal", "general", "quality", "gguf"],
                "taskSupport": ["txt2img"],
                "sizeGb": 12.7,
                "recommendedResolution": "1024x1024",
                "note": "GGUF Q8_0 — near-bf16 transformer quality; text encoders/VAE still make the full FLUX runtime memory-heavy.",
                "estimatedGenerationSeconds": 4.8,
                "releaseDate": "2024-09",
            },
            {
                "id": "black-forest-labs/FLUX.1-schnell-mflux",
                "familyId": "flux-fast",
                "name": "FLUX.1 Schnell · mflux (MLX)",
                "provider": "Black Forest Labs · mflux",
                "repo": "black-forest-labs/FLUX.1-schnell",
                "engine": "mflux",
                "link": "https://github.com/filipstrand/mflux",
                "runtime": "mflux (MLX native)",
                "styleTags": ["photoreal", "general", "fast", "apple-silicon"],
                "taskSupport": ["txt2img"],
                "sizeGb": 23.7,
                "recommendedResolution": "1024x1024",
                "note": "Apple Silicon only — native MLX runtime, 2-3x faster than diffusers+MPS.",
                "estimatedGenerationSeconds": 2.4,
                "releaseDate": "2024-10",
            },
        ],
    },
    {
        "id": "flux-dev",
        "name": "FLUX.1 Dev",
        "provider": "Black Forest Labs",
        "headline": "High-fidelity guidance-distilled model for detailed, prompt-faithful generation.",
        "summary": "Balanced option for the eventual production runtime when you want stronger final image quality than the fast path.",
        "updatedLabel": "Curated quality pick",
        "badges": ["Balanced", "General", "Detailed"],
        "defaultVariantId": "black-forest-labs/FLUX.1-dev",
        "variants": [
            {
                "id": "black-forest-labs/FLUX.1-dev",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev",
                "provider": "Black Forest Labs",
                "repo": "black-forest-labs/FLUX.1-dev",
                "link": "https://huggingface.co/black-forest-labs/FLUX.1-dev",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["general", "detailed", "balanced"],
                "taskSupport": ["txt2img"],
                "sizeGb": 23.8,
                "recommendedResolution": "1024x1024",
                "note": "Quality-oriented generalist for the curated image lineup.",
                "estimatedGenerationSeconds": 7.4,
                "releaseDate": "2024-08",
            },
            {
                "id": "black-forest-labs/FLUX.1-dev-gguf-q4km",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev · GGUF Q4_K_M",
                "provider": "Black Forest Labs · city96",
                "repo": "black-forest-labs/FLUX.1-dev",
                "ggufRepo": "city96/FLUX.1-dev-gguf",
                "ggufFile": "flux1-dev-Q4_K_M.gguf",
                "link": "https://huggingface.co/city96/FLUX.1-dev-gguf",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["general", "detailed", "gguf"],
                "taskSupport": ["txt2img"],
                "sizeGb": 6.8,
                "recommendedResolution": "1024x1024",
                "note": "GGUF Q4_K_M — quantizes the FLUX Dev transformer; expect the full diffusers pipeline to remain memory-heavy from text encoders/VAE.",
                "estimatedGenerationSeconds": 9.0,
                "releaseDate": "2024-09",
            },
            {
                "id": "black-forest-labs/FLUX.1-dev-gguf-q6k",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev · GGUF Q6_K",
                "provider": "Black Forest Labs · city96",
                "repo": "black-forest-labs/FLUX.1-dev",
                "ggufRepo": "city96/FLUX.1-dev-gguf",
                "ggufFile": "flux1-dev-Q6_K.gguf",
                "link": "https://huggingface.co/city96/FLUX.1-dev-gguf",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["general", "detailed", "quality", "gguf"],
                "taskSupport": ["txt2img"],
                "sizeGb": 9.9,
                "recommendedResolution": "1024x1024",
                "note": "GGUF Q6_K — mid-point between Q4 size and Q8 transformer quality; FLUX text encoders/VAE still dominate runtime memory.",
                "estimatedGenerationSeconds": 8.4,
                "releaseDate": "2024-09",
            },
            {
                "id": "black-forest-labs/FLUX.1-dev-gguf-q8",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev · GGUF Q8_0",
                "provider": "Black Forest Labs · city96",
                "repo": "black-forest-labs/FLUX.1-dev",
                "ggufRepo": "city96/FLUX.1-dev-gguf",
                "ggufFile": "flux1-dev-Q8_0.gguf",
                "link": "https://huggingface.co/city96/FLUX.1-dev-gguf",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["general", "detailed", "quality", "gguf"],
                "taskSupport": ["txt2img"],
                "sizeGb": 12.7,
                "recommendedResolution": "1024x1024",
                "note": "GGUF Q8_0 — near-bf16 transformer quality; text encoders/VAE still make the full FLUX runtime memory-heavy.",
                "estimatedGenerationSeconds": 7.8,
                "releaseDate": "2024-09",
            },
            {
                "id": "black-forest-labs/FLUX.1-dev-mflux",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev · mflux (MLX)",
                "provider": "Black Forest Labs · mflux",
                "repo": "black-forest-labs/FLUX.1-dev",
                "engine": "mflux",
                "link": "https://github.com/filipstrand/mflux",
                "runtime": "mflux (MLX native)",
                "styleTags": ["general", "detailed", "apple-silicon"],
                "taskSupport": ["txt2img"],
                "sizeGb": 23.8,
                "recommendedResolution": "1024x1024",
                "note": "Apple Silicon only — native MLX runtime, 2-3x faster than diffusers+MPS.",
                "estimatedGenerationSeconds": 4.5,
                "releaseDate": "2024-10",
            },
            # FU-019 distill LoRAs. Drop FLUX.1-dev from 25-step base
            # quality to 8-step quality. Stacks cleanly with NF4
            # (CUDA) / int8wo (MPS) / GGUF — the LoRA is loaded onto
            # the already-quantized transformer at fuse time. CFG and
            # step counts come from the LoRA author's recommended
            # workflow.
            {
                "id": "black-forest-labs/FLUX.1-dev-hyper-sd-8step",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev · Hyper-SD 8-step",
                "provider": "Black Forest Labs · ByteDance",
                "repo": "black-forest-labs/FLUX.1-dev",
                "loraRepo": "ByteDance/Hyper-SD",
                "loraFile": "Hyper-FLUX.1-dev-8steps-lora.safetensors",
                "loraScale": 0.125,
                "defaultSteps": 8,
                "cfgOverride": 3.5,
                "link": "https://huggingface.co/ByteDance/Hyper-SD",
                "runtime": "diffusers + Hyper-SD LoRA",
                "styleTags": ["general", "detailed", "fast", "lora"],
                "taskSupport": ["txt2img"],
                "sizeGb": 23.8,
                "recommendedResolution": "1024x1024",
                "note": (
                    "8-step Hyper-SD distillation LoRA fused into FLUX.1 Dev. "
                    "Matches base FLUX.1 Dev 25-step quality at ≈3× speed. "
                    "Stacks with NF4/int8wo/GGUF."
                ),
                "estimatedGenerationSeconds": 2.4,
                "releaseDate": "2024-10",
            },
            {
                "id": "black-forest-labs/FLUX.1-dev-turbo-alpha",
                "familyId": "flux-dev",
                "name": "FLUX.1 Dev · Turbo Alpha",
                "provider": "Black Forest Labs · alimama-creative",
                "repo": "black-forest-labs/FLUX.1-dev",
                "loraRepo": "alimama-creative/FLUX.1-Turbo-Alpha",
                "loraFile": "diffusion_pytorch_model.safetensors",
                "loraScale": 1.0,
                "defaultSteps": 8,
                "cfgOverride": 3.5,
                "link": "https://huggingface.co/alimama-creative/FLUX.1-Turbo-Alpha",
                "runtime": "diffusers + FLUX.1-Turbo-Alpha LoRA",
                "styleTags": ["general", "detailed", "fast", "lora"],
                "taskSupport": ["txt2img"],
                "sizeGb": 23.8,
                "recommendedResolution": "1024x1024",
                "note": (
                    "alimama's 8-step Turbo Alpha LoRA fused into FLUX.1 Dev. "
                    "Same wall-time win as Hyper-SD with slightly different "
                    "stylistic bias — try both and pick by output."
                ),
                "estimatedGenerationSeconds": 2.4,
                "releaseDate": "2025-02",
            },
        ],
    },
    {
        "id": "sd35-medium",
        "name": "Stable Diffusion 3.5 Medium",
        "provider": "Stability AI",
        "headline": "Latest Stability model optimised for consumer hardware with MMDiT architecture.",
        "summary": "Modern architecture with strong prompt adherence and detail at a manageable model size for local use.",
        "updatedLabel": "Curated balanced pick",
        "badges": ["MMDiT", "Balanced", "Modern"],
        "defaultVariantId": "stabilityai/stable-diffusion-3.5-medium",
        "variants": [
            {
                "id": "stabilityai/stable-diffusion-3.5-medium",
                "familyId": "sd35-medium",
                "name": "Stable Diffusion 3.5 Medium",
                "provider": "Stability AI",
                "repo": "stabilityai/stable-diffusion-3.5-medium",
                "link": "https://huggingface.co/stabilityai/stable-diffusion-3.5-medium",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["general", "detailed", "modern"],
                "taskSupport": ["txt2img"],
                "sizeGb": 11.9,
                "recommendedResolution": "1024x1024",
                "note": "Latest Stability offering targeting a good quality-to-resource balance.",
                "estimatedGenerationSeconds": 5.8,
                "releaseDate": "2024-10",
            }
        ],
    },
    {
        "id": "sd35-turbo",
        "name": "Stable Diffusion 3.5 Large Turbo",
        "provider": "Stability AI",
        "headline": "Distilled large model for fast, high-quality generation in fewer inference steps.",
        "summary": "Best pick when you want near-instant drafts at higher fidelity than older turbo models.",
        "updatedLabel": "Curated speed pick",
        "badges": ["Turbo", "Fast", "High quality"],
        "defaultVariantId": "stabilityai/stable-diffusion-3.5-large-turbo",
        "variants": [
            {
                "id": "stabilityai/stable-diffusion-3.5-large-turbo",
                "familyId": "sd35-turbo",
                "name": "Stable Diffusion 3.5 Large Turbo",
                "provider": "Stability AI",
                "repo": "stabilityai/stable-diffusion-3.5-large-turbo",
                "link": "https://huggingface.co/stabilityai/stable-diffusion-3.5-large-turbo",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["fast", "quality", "general"],
                "taskSupport": ["txt2img"],
                "sizeGb": 16.5,
                "recommendedResolution": "1024x1024",
                "note": "Fastest high-fidelity model in the curated set.",
                "estimatedGenerationSeconds": 3.1,
                "releaseDate": "2024-10",
            }
        ],
    },
    {
        "id": "sdxl-balanced",
        "name": "SDXL Balanced",
        "provider": "Stability AI",
        "headline": "General-purpose SDXL model for reliable, high-quality everyday image generation.",
        "summary": "Established baseline with wide ecosystem support, LoRA compatibility, and proven quality.",
        "updatedLabel": "Curated classic",
        "badges": ["Balanced", "General", "Detailed"],
        "defaultVariantId": "stabilityai/stable-diffusion-xl-base-1.0",
        "variants": [
            {
                "id": "stabilityai/stable-diffusion-xl-base-1.0",
                "familyId": "sdxl-balanced",
                "name": "Stable Diffusion XL Base 1.0",
                "provider": "Stability AI",
                "repo": "stabilityai/stable-diffusion-xl-base-1.0",
                "link": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
                "runtime": "Stub diffusion pipeline",
                "styleTags": ["general", "detailed", "balanced"],
                "taskSupport": ["txt2img"],
                "sizeGb": 13.1,
                "recommendedResolution": "1024x1024",
                "note": "Widely adopted SDXL baseline with strong community and LoRA ecosystem.",
                "estimatedGenerationSeconds": 7.4,
                "releaseDate": "2023-07",
            }
        ],
    },
]

LATEST_IMAGE_TRACKED_SEEDS: list[dict[str, Any]] = [
    {
        "repo": "baidu/ERNIE-Image",
        "name": "ERNIE-Image",
        "provider": "Baidu",
        "styleTags": ["general", "detailed"],
        "taskSupport": ["txt2img"],
        "sizeGb": 29.43,
        "runtimeFootprintGb": 24.0,
        "runtimeFootprintMpsGb": 32.0,
        "runtimeFootprintCpuGb": 36.0,
        "coreWeightsGb": 29.43,
        "repoSizeGb": 29.47,
        "recommendedResolution": "1024x1024",
        "note": "Tracked current text-to-image DiT release from Baidu.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-04",
    },
    {
        "repo": "baidu/ERNIE-Image-Turbo",
        "name": "ERNIE-Image-Turbo",
        "provider": "Baidu",
        "styleTags": ["general", "fast"],
        "taskSupport": ["txt2img"],
        "sizeGb": 29.43,
        "runtimeFootprintGb": 24.0,
        "runtimeFootprintMpsGb": 32.0,
        "runtimeFootprintCpuGb": 36.0,
        "coreWeightsGb": 29.43,
        "repoSizeGb": 29.47,
        "recommendedResolution": "1024x1024",
        "note": "Tracked faster ERNIE-Image lane for current local image generation discovery.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-04",
    },
    {
        "repo": "NucleusAI/Nucleus-Image",
        "name": "Nucleus-Image",
        "provider": "NucleusAI",
        "styleTags": ["general", "detailed"],
        "taskSupport": ["txt2img"],
        "sizeGb": 48.09,
        "runtimeFootprintGb": 48.0,
        "runtimeFootprintMpsGb": 55.0,
        "runtimeFootprintCpuGb": 60.0,
        "coreWeightsGb": 48.09,
        "repoSizeGb": 48.11,
        "recommendedResolution": "1024x1024",
        "note": "Tracked current diffusers-compatible text-to-image release.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-04",
    },
    {
        "repo": "black-forest-labs/FLUX.2-dev",
        "name": "FLUX.2 Dev",
        "provider": "Black Forest Labs",
        "styleTags": ["general", "detailed", "flux"],
        "taskSupport": ["txt2img", "img2img"],
        "sizeGb": 64.7,
        "runtimeFootprintGb": 65.0,
        "runtimeFootprintMpsGb": 78.0,
        "runtimeFootprintCpuGb": 90.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked FLUX.2 generation-and-editing release.",
        "gated": True,
        "pipelineTag": "image-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-02",
    },
    {
        "repo": "black-forest-labs/FLUX.2-klein-9B",
        "name": "FLUX.2 Klein 9B",
        "provider": "Black Forest Labs",
        "styleTags": ["general", "flux", "fast"],
        "taskSupport": ["txt2img", "img2img"],
        "sizeGb": 49.23,
        "runtimeFootprintGb": 49.0,
        "runtimeFootprintMpsGb": 55.0,
        "runtimeFootprintCpuGb": 64.0,
        "coreWeightsGb": 49.23,
        "repoSizeGb": 49.26,
        "recommendedResolution": "1024x1024",
        "note": "Tracked smaller FLUX.2 lane.",
        "gated": False,
        "pipelineTag": "image-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-02",
    },
    {
        "repo": "fal/FLUX.2-dev-Turbo",
        "name": "FLUX.2 Dev · Turbo",
        "provider": "Black Forest Labs · fal",
        "styleTags": ["general", "fast", "flux"],
        "taskSupport": ["txt2img", "img2img"],
        "sizeGb": 49.5,
        "runtimeFootprintGb": 50.0,
        "runtimeFootprintMpsGb": 60.0,
        "runtimeFootprintCpuGb": 70.0,
        "coreWeightsGb": 49.5,
        "repoSizeGb": 49.6,
        "recommendedResolution": "1024x1024",
        "note": (
            "fal's Turbo distillation of FLUX.2 Dev — 8-step Turbo Alpha "
            "matches the base 25-step quality. Tracked for catalog refresh "
            "(FU-019 catalog round)."
        ),
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-12",
    },
    {
        "repo": "Tongyi-MAI/Z-Image-Turbo",
        "name": "Z-Image-Turbo",
        "provider": "Tongyi-MAI",
        "styleTags": ["general", "fast"],
        "taskSupport": ["txt2img"],
        "sizeGb": 30.58,
        "runtimeFootprintGb": 16.0,
        "runtimeFootprintMpsGb": 20.0,
        "runtimeFootprintCpuGb": 24.0,
        "coreWeightsGb": 30.58,
        "repoSizeGb": 30.64,
        "recommendedResolution": "1024x1024",
        "note": "Tracked current Z-Image turbo text-to-image release.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-01",
    },
    {
        "repo": "Tongyi-MAI/Z-Image",
        "name": "Z-Image",
        "provider": "Tongyi-MAI",
        "styleTags": ["general", "detailed"],
        "taskSupport": ["txt2img"],
        "sizeGb": 19.11,
        "runtimeFootprintGb": 22.0,
        "runtimeFootprintMpsGb": 24.0,
        "runtimeFootprintCpuGb": 30.0,
        "coreWeightsGb": 19.11,
        "repoSizeGb": 19.14,
        "recommendedResolution": "1024x1024",
        "note": "Tracked current Z-Image text-to-image release.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2026-01",
    },
    {
        "repo": "Qwen/Qwen-Image-Edit-2511",
        "name": "Qwen-Image-Edit-2511",
        "provider": "Qwen",
        "styleTags": ["edit", "qwenimage", "general"],
        "taskSupport": ["img2img"],
        "sizeGb": 57.7,
        "runtimeFootprintGb": 58.0,
        "runtimeFootprintMpsGb": 72.0,
        "runtimeFootprintCpuGb": 72.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked newer Qwen image editing release with improved consistency.",
        "gated": False,
        "pipelineTag": "image-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-12",
    },
    {
        "repo": "Qwen/Qwen-Image",
        "name": "Qwen-Image",
        "provider": "Qwen",
        "styleTags": ["general", "detailed", "qwenimage"],
        "taskSupport": ["txt2img"],
        "sizeGb": 57.7,
        "runtimeFootprintGb": 58.0,
        "runtimeFootprintMpsGb": 72.0,
        "runtimeFootprintCpuGb": 72.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked diffusers-native Qwen image generation family.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-08",
    },
    {
        "repo": "Qwen/Qwen-Image-Edit",
        "name": "Qwen-Image-Edit",
        "provider": "Qwen",
        "styleTags": ["edit", "qwenimage", "general"],
        "taskSupport": ["img2img"],
        "sizeGb": 57.7,
        "runtimeFootprintGb": 58.0,
        "runtimeFootprintMpsGb": 72.0,
        "runtimeFootprintCpuGb": 72.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked Qwen edit lane so Image Discover can surface newer editing-capable models too.",
        "gated": False,
        "pipelineTag": "image-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-08",
    },
    {
        "repo": "HiDream-ai/HiDream-I1-Full",
        "name": "HiDream-I1 Full",
        "provider": "HiDream AI",
        "styleTags": ["hidream", "detailed", "quality"],
        "taskSupport": ["txt2img"],
        "sizeGb": 47.2,
        "runtimeFootprintGb": 58.0,
        "runtimeFootprintMpsGb": 62.0,
        "runtimeFootprintCpuGb": 70.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked larger open-image generation lane from the HiDream family.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-04",
    },
    {
        "repo": "zai-org/GLM-Image",
        "name": "GLM-Image",
        "provider": "Z.ai",
        "styleTags": ["general", "edit", "detailed"],
        "taskSupport": ["txt2img", "img2img"],
        "sizeGb": 35.8,
        "runtimeFootprintGb": 40.0,
        "runtimeFootprintMpsGb": 45.0,
        "runtimeFootprintCpuGb": 52.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked unified generation-and-editing lane from the GLM image family.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
    },
    {
        "repo": "Efficient-Large-Model/Sana_Sprint_0.6B_1024px_diffusers",
        "name": "Sana Sprint 0.6B",
        "provider": "Efficient-Large-Model",
        "styleTags": ["sana", "fast", "small"],
        "taskSupport": ["txt2img"],
        "sizeGb": 7.7,
        "runtimeFootprintGb": 8.0,
        "runtimeFootprintMpsGb": 10.0,
        "runtimeFootprintCpuGb": 12.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked smaller Sana Sprint lane for faster local image generation.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-03",
    },
    {
        "repo": "Efficient-Large-Model/Sana_Sprint_1.6B_1024px_diffusers",
        "name": "Sana Sprint 1.6B",
        "provider": "Efficient-Large-Model",
        "styleTags": ["sana", "fast", "detailed"],
        "taskSupport": ["txt2img"],
        "sizeGb": 9.74,
        "runtimeFootprintGb": 10.0,
        "runtimeFootprintMpsGb": 12.0,
        "runtimeFootprintCpuGb": 15.0,
        "recommendedResolution": "1024x1024",
        "note": "Tracked larger Sana Sprint lane with a better quality-to-speed balance.",
        "gated": False,
        "pipelineTag": "text-to-image",
        "updatedLabel": "Tracked latest",
        "releaseDate": "2025-03",
    },
]
