from __future__ import annotations

from typing import Any


MODEL_FAMILIES: list[dict[str, Any]] = [
    {
        "id": "gemma-4",
        "name": "Gemma 4",
        "provider": "Google",
        "headline": "New multimodal Gemma family for reasoning, coding, and on-device workflows.",
        "summary": "Strong general-purpose family with compact edge variants and a larger A4B option for workstation-class use.",
        "description": (
            "Gemma 4 covers compact edge deployment through larger multimodal reasoning models. "
            "It is a good fit when you want a modern generalist with long context and strong coding support."
        ),
        "updatedLabel": "Updated 3 days ago",
        "popularityLabel": "323k downloads",
        "likesLabel": "58 likes",
        "badges": ["Staff pick", "Vision", "Reasoning"],
        "capabilities": ["reasoning", "vision", "coding", "multilingual"],
        "defaultVariantId": "google/gemma-4-26B-A4B-it",
        "variants": [
            {
                "id": "google/gemma-4-E4B-it",
                "name": "Gemma 4 E4B Instruct",
                "repo": "google/gemma-4-E4B-it",
                "link": "https://huggingface.co/google/gemma-4-E4B-it",
                "paramsB": 4.5,
                "sizeGb": 5.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["vision", "reasoning", "tool-use"],
                "note": "Compact Gemma 4 variant for laptops and small desktops.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "google/gemma-4-12B-it",
                "name": "Gemma 4 12B Instruct",
                "repo": "google/gemma-4-12B-it",
                "link": "https://huggingface.co/google/gemma-4-12B-it",
                "paramsB": 12.0,
                "sizeGb": 14.8,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["vision", "reasoning", "coding"],
                "note": "Higher quality Gemma 4 option for larger local rigs.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "google/gemma-4-26B-A4B-it",
                "name": "Gemma 4 26B A4B Instruct",
                "repo": "google/gemma-4-26B-A4B-it",
                "link": "https://huggingface.co/google/gemma-4-26B-A4B-it",
                "paramsB": 26.0,
                "sizeGb": 28.1,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["vision", "reasoning", "coding", "agents"],
                "note": "Large multimodal Gemma 4 variant for workstation-class setups.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "mlx-community/gemma-4-26b-a4b-it-5bit",
                "name": "Gemma 4 26B A4B MLX 5-bit",
                "repo": "mlx-community/gemma-4-26b-a4b-it-5bit",
                "link": "https://huggingface.co/mlx-community/gemma-4-26b-a4b-it-5bit",
                "paramsB": 26.0,
                "sizeGb": 18.5,
                "format": "MLX",
                "quantization": "5-bit",
                "capabilities": ["vision", "reasoning", "coding", "agents"],
                "note": "Community MLX conversion of the instruct checkpoint, with a bundled chat template for ready-to-run desktop chat.",
                "contextWindow": "256K",
                "launchMode": "direct",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Gemma 4 is built for reasoning, coding, and multimodal understanding.",
            "Small variants target local deployment; larger variants suit workstation-class hardware.",
            "Official transformer repos still route through conversion, while community MLX variants can run directly when available.",
        ],
    },
    {
        "id": "qwen-3-5",
        "name": "Qwen 3.5",
        "provider": "Qwen",
        "headline": "Hybrid reasoning family with long context and strong agent support.",
        "summary": "Useful when you want modern reasoning and coding performance with a wide spread of model sizes.",
        "description": (
            "Qwen 3.5 spans compact and MoE-heavy variants with long context support. "
            "It fits well for agent-style workflows, tool use, and coding-heavy chats."
        ),
        "updatedLabel": "Updated this month",
        "popularityLabel": "Featured family",
        "likesLabel": "Qwen official",
        "badges": ["Reasoning", "Coding", "Long context"],
        "capabilities": ["reasoning", "coding", "tool-use", "vision"],
        "defaultVariantId": "Qwen/Qwen3.5-9B",
        "variants": [
            {
                "id": "Qwen/Qwen3.5-4B",
                "name": "Qwen3.5 4B",
                "repo": "Qwen/Qwen3.5-4B",
                "link": "https://huggingface.co/Qwen/Qwen3.5-4B",
                "paramsB": 4.0,
                "sizeGb": 5.1,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "tool-use"],
                "note": "Smaller Qwen 3.5 variant with strong utility for everyday local work.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen3.5-9B",
                "name": "Qwen3.5 9B",
                "repo": "Qwen/Qwen3.5-9B",
                "link": "https://huggingface.co/Qwen/Qwen3.5-9B",
                "paramsB": 9.0,
                "sizeGb": 10.9,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "vision", "video", "tool-use"],
                "note": "Balanced Qwen 3.5 option for serious local chat, code, and agent tasks.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "mlx-community/Qwen3.5-9B-4bit",
                "name": "Qwen3.5 9B MLX 4-bit",
                "repo": "mlx-community/Qwen3.5-9B-4bit",
                "link": "https://huggingface.co/mlx-community/Qwen3.5-9B-4bit",
                "paramsB": 9.0,
                "sizeGb": 6.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["reasoning", "coding", "vision", "video", "tool-use"],
                "note": "Community MLX conversion for Apple Silicon with a much quicker local launch path.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "mlx",
            },
            {
                "id": "lmstudio-community/Qwen3.5-9B-GGUF",
                "name": "Qwen3.5 9B GGUF",
                "repo": "lmstudio-community/Qwen3.5-9B-GGUF",
                "link": "https://huggingface.co/lmstudio-community/Qwen3.5-9B-GGUF",
                "paramsB": 9.0,
                "sizeGb": 5.8,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "coding", "tool-use"],
                "note": "Community GGUF pack with ready-made quantizations for quick llama.cpp runs.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
            {
                "id": "Qwen/Qwen3.5-35B-A3B-FP8",
                "name": "Qwen3.5 35B A3B",
                "repo": "Qwen/Qwen3.5-35B-A3B-FP8",
                "link": "https://huggingface.co/Qwen/Qwen3.5-35B-A3B-FP8",
                "paramsB": 35.0,
                "sizeGb": 22.8,
                "format": "Transformers",
                "quantization": "FP8",
                "capabilities": ["reasoning", "coding", "vision", "agents"],
                "note": "Sparse MoE-style Qwen 3.5 variant tuned for high-end local or server workflows.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Qwen 3.5 is a reasoning-first family with long context and strong coding support.",
            "Thinking mode is model-native, so it works well for agent-style threads and tool-rich prompts.",
            "The catalog now mixes official transformer repos with community GGUF and MLX variants so you can go straight to a runnable format when one exists.",
        ],
    },
    {
        "id": "nemotron-3-nano",
        "name": "Nemotron 3 Nano",
        "provider": "NVIDIA",
        "headline": "Compact reasoning-first family aimed at efficient local deployment.",
        "summary": "Good fit when you want a modern small model that still feels capable in chat and tool use.",
        "description": (
            "Nemotron 3 Nano focuses on local efficiency and reasoning utility. "
            "The GGUF variant is ready to use directly in the local llama.cpp path, while the BF16 weights can feed conversion workflows."
        ),
        "updatedLabel": "Updated 2 weeks ago",
        "popularityLabel": "New release",
        "likesLabel": "NVIDIA official",
        "badges": ["Popular", "Reasoning", "Local-first"],
        "capabilities": ["reasoning", "tool-use", "chat"],
        "defaultVariantId": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
        "variants": [
            {
                "id": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
                "name": "Nemotron 3 Nano 4B GGUF",
                "repo": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
                "link": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
                "paramsB": 4.0,
                "sizeGb": 3.1,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "chat", "tool-use"],
                "note": "Direct-load GGUF path for fast local trials and thread switching.",
                "contextWindow": "128K",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
            {
                "id": "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
                "name": "Nemotron 3 Nano 4B BF16",
                "repo": "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
                "link": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
                "paramsB": 4.0,
                "sizeGb": 8.2,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "chat", "tool-use"],
                "note": "Official BF16 weights if you want to convert into an MLX-friendly local artifact.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
                "name": "Nemotron 3 Nano 30B A3B FP8",
                "repo": "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
                "link": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
                "paramsB": 30.0,
                "sizeGb": 35.0,
                "format": "Transformers",
                "quantization": "FP8",
                "capabilities": ["reasoning", "thinking", "tool-use", "coding", "agents"],
                "note": "Larger official Nemotron 3 Nano checkpoint with configurable reasoning traces and very long context.",
                "contextWindow": "1M",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
                "name": "Nemotron 3 Nano 30B A3B GGUF",
                "repo": "lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
                "link": "https://huggingface.co/lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
                "paramsB": 30.0,
                "sizeGb": 24.5,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "thinking", "tool-use", "coding", "agents"],
                "note": "Community GGUF conversion for the larger Nemotron 3 Nano release when you want a ready llama.cpp path.",
                "contextWindow": "1M",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
        ],
        "readme": [
            "Nemotron 3 Nano is built for compact local deployments without falling back to obviously weak outputs.",
            "The family now includes both the smaller 4B checkpoints and the newer 30B A3B release.",
            "Official checkpoints remain available for conversion, while community GGUF packs give you a direct runtime path.",
        ],
    },
    {
        "id": "devstral-small",
        "name": "Devstral Small",
        "provider": "Mistral AI",
        "headline": "Agentic coding model family tuned for software engineering tasks.",
        "summary": "Best when the conversation is code-heavy and you want a thread-specific model for repo work.",
        "description": (
            "Devstral focuses on software engineering workflows and tool-using assistants. "
            "The GGUF release is directly usable, and the BF16 release can feed conversion-oriented setups."
        ),
        "updatedLabel": "Updated 3 weeks ago",
        "popularityLabel": "Trending with coding users",
        "likesLabel": "Mistral official",
        "badges": ["Coding", "Agents", "Tool use"],
        "capabilities": ["coding", "agents", "tool-use"],
        "defaultVariantId": "mistralai/Devstral-Small-2507_gguf",
        "variants": [
            {
                "id": "mistralai/Devstral-Small-2507_gguf",
                "name": "Devstral Small 2507 GGUF",
                "repo": "mistralai/Devstral-Small-2507_gguf",
                "link": "https://huggingface.co/mistralai/Devstral-Small-2507_gguf",
                "paramsB": 24.0,
                "sizeGb": 15.7,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["coding", "agents", "tool-use"],
                "note": "Direct GGUF path for local coding threads and repo-centric workflows.",
                "contextWindow": "128K",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
            {
                "id": "mistralai/Devstral-Small-2507",
                "name": "Devstral Small 2507 BF16",
                "repo": "mistralai/Devstral-Small-2507",
                "link": "https://huggingface.co/mistralai/Devstral-Small-2507",
                "paramsB": 24.0,
                "sizeGb": 29.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["coding", "agents", "tool-use"],
                "note": "Official BF16 weights for conversion-oriented local setups.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Devstral is tuned for software engineering and tool-using workflows.",
            "Use the GGUF variant when you want the quickest path into local code threads.",
            "Use the BF16 repo when you want to convert into an MLX artifact instead of running GGUF.",
        ],
    },
    {
        "id": "qwen3-coder",
        "name": "Qwen3 Coder",
        "provider": "Qwen",
        "headline": "Code-specialised Qwen3 with strong agentic and tool-use support.",
        "summary": "Large official coding checkpoint with BF16 and FP8 repos for high-end local and server workflows.",
        "description": (
            "Qwen3 Coder is optimised for software engineering workflows with agentic tool use, "
            "large context windows, and configurable thinking depth. Great for local coding assistants."
        ),
        "updatedLabel": "Updated Feb 2026",
        "popularityLabel": "639k downloads",
        "likesLabel": "1.3k likes",
        "badges": ["Coding", "Agents", "Tool-use"],
        "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
        "defaultVariantId": "Qwen/Qwen3-Coder-Next-FP8",
        "variants": [
            {
                "id": "Qwen/Qwen3-Coder-Next",
                "name": "Qwen3 Coder Next BF16",
                "repo": "Qwen/Qwen3-Coder-Next",
                "link": "https://huggingface.co/Qwen/Qwen3-Coder-Next",
                "paramsB": 75.0,
                "sizeGb": 148.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
                "note": "Full official Qwen3 Coder Next checkpoint for very high-memory workstations and servers.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen3-Coder-Next-FP8",
                "name": "Qwen3 Coder Next FP8",
                "repo": "Qwen/Qwen3-Coder-Next-FP8",
                "link": "https://huggingface.co/Qwen/Qwen3-Coder-Next-FP8",
                "paramsB": 75.0,
                "sizeGb": 74.9,
                "format": "Transformers",
                "quantization": "FP8",
                "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
                "note": "Smaller official FP8 repo for the same Qwen3 Coder Next family when you want the lighter download.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Qwen3 Coder Next is purpose-built for software engineering with function calling and agentic workflows.",
            "Choose the FP8 repo when you want the lighter official download; choose BF16 when you want the full checkpoint.",
            "These official Next repos replace the older provisional 8B and 32B catalog placeholders.",
        ],
    },
    {
        "id": "qwen-2-5",
        "name": "Qwen 2.5",
        "provider": "Qwen",
        "headline": "Versatile general-purpose family with chat, coding, and multilingual variants.",
        "summary": "Mature, well-tested family spanning 0.5B to 72B with strong community support.",
        "description": (
            "Qwen 2.5 is a proven workhorse family that covers everything from tiny edge models "
            "to large multilingual reasoners. Excellent GGUF availability in the community."
        ),
        "updatedLabel": "Updated 2 weeks ago",
        "popularityLabel": "890k downloads",
        "likesLabel": "156 likes",
        "badges": ["Popular", "Coding", "Multilingual"],
        "capabilities": ["chat", "coding", "multilingual", "reasoning", "tool-use"],
        "defaultVariantId": "Qwen/Qwen2.5-7B-Instruct",
        "variants": [
            {
                "id": "Qwen/Qwen2.5-3B-Instruct",
                "name": "Qwen 2.5 3B Instruct",
                "repo": "Qwen/Qwen2.5-3B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct",
                "paramsB": 3.0,
                "sizeGb": 3.6,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "coding", "multilingual"],
                "note": "Ultra-compact variant for quick prototyping and edge deployments.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen2.5-7B-Instruct",
                "name": "Qwen 2.5 7B Instruct",
                "repo": "Qwen/Qwen2.5-7B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
                "paramsB": 7.0,
                "sizeGb": 8.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "coding", "reasoning", "multilingual"],
                "note": "Well-rounded 7B for general chat and coding on 16GB+ machines.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen2.5-Coder-7B-Instruct",
                "name": "Qwen 2.5 Coder 7B",
                "repo": "Qwen/Qwen2.5-Coder-7B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
                "paramsB": 7.0,
                "sizeGb": 8.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["coding", "tool-use", "agents"],
                "note": "Code-focused 7B with function calling and agentic support.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen2.5-32B-Instruct",
                "name": "Qwen 2.5 32B Instruct",
                "repo": "Qwen/Qwen2.5-32B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct",
                "paramsB": 32.0,
                "sizeGb": 38.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "coding", "reasoning", "multilingual", "tool-use"],
                "note": "Large Qwen 2.5 for workstation setups needing quality and breadth.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Qwen 2.5 is a mature, well-supported family with extensive community GGUF availability.",
            "The Coder variant is specialised for software engineering and function calling.",
        ],
    },
    {
        "id": "llama-3-3",
        "name": "Llama 3.3",
        "provider": "Meta",
        "headline": "Meta's flagship open-weight model with strong reasoning and multilingual support.",
        "summary": "High-quality 70B distilled into efficient variants. Industry standard for local inference.",
        "description": (
            "Llama 3.3 brings Meta's strongest open-weight reasoning to local hardware. "
            "The 70B is the gold standard; community quantisations make it accessible on Apple Silicon."
        ),
        "updatedLabel": "Updated 3 weeks ago",
        "popularityLabel": "1.2M downloads",
        "likesLabel": "312 likes",
        "badges": ["Popular", "Reasoning", "Multilingual"],
        "capabilities": ["chat", "reasoning", "coding", "multilingual", "tool-use"],
        "defaultVariantId": "meta-llama/Llama-3.3-70B-Instruct",
        "variants": [
            {
                "id": "meta-llama/Llama-3.3-70B-Instruct",
                "name": "Llama 3.3 70B Instruct",
                "repo": "meta-llama/Llama-3.3-70B-Instruct",
                "link": "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
                "paramsB": 70.0,
                "sizeGb": 84.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "reasoning", "coding", "multilingual", "tool-use"],
                "note": "Full 70B for 128GB+ machines. Highest quality open-weight reasoning.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "mlx-community/Llama-3.3-70B-Instruct-4bit",
                "name": "Llama 3.3 70B MLX 4-bit",
                "repo": "mlx-community/Llama-3.3-70B-Instruct-4bit",
                "link": "https://huggingface.co/mlx-community/Llama-3.3-70B-Instruct-4bit",
                "paramsB": 70.0,
                "sizeGb": 40.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["chat", "reasoning", "coding", "multilingual", "tool-use"],
                "note": "4-bit quantisation for 64GB machines. Good quality/size tradeoff.",
                "contextWindow": "128K",
                "launchMode": "direct",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Llama 3.3 is Meta's strongest open-weight model, widely used as a benchmark.",
            "The 4-bit MLX variant fits on 64GB Apple Silicon with room for context.",
        ],
    },
    {
        "id": "phi-4",
        "name": "Phi 4",
        "provider": "Microsoft",
        "headline": "Compact reasoning models with strong STEM and coding performance.",
        "summary": "Small-but-capable family that punches above its weight on reasoning benchmarks.",
        "description": (
            "Phi 4 delivers impressive reasoning and STEM performance in compact sizes. "
            "Great for resource-constrained setups that need quality reasoning."
        ),
        "updatedLabel": "Updated 2 weeks ago",
        "popularityLabel": "420k downloads",
        "likesLabel": "89 likes",
        "badges": ["Reasoning", "Compact", "STEM"],
        "capabilities": ["reasoning", "coding", "chat", "multilingual"],
        "defaultVariantId": "microsoft/phi-4",
        "variants": [
            {
                "id": "microsoft/phi-4",
                "name": "Phi 4 14B",
                "repo": "microsoft/phi-4",
                "link": "https://huggingface.co/microsoft/phi-4",
                "paramsB": 14.0,
                "sizeGb": 16.8,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "chat"],
                "note": "14B model that rivals much larger models on STEM and reasoning tasks.",
                "contextWindow": "16K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "mlx-community/phi-4-4bit",
                "name": "Phi 4 14B MLX 4-bit",
                "repo": "mlx-community/phi-4-4bit",
                "link": "https://huggingface.co/mlx-community/phi-4-4bit",
                "paramsB": 14.0,
                "sizeGb": 8.5,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["reasoning", "coding", "chat"],
                "note": "Compact 4-bit variant that runs well on 16GB machines.",
                "contextWindow": "16K",
                "launchMode": "direct",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Phi 4 punches above its weight on reasoning and STEM benchmarks.",
            "The 4-bit MLX variant is one of the best options for 16GB MacBooks.",
        ],
    },
    {
        "id": "mistral-nemo",
        "name": "Mistral Nemo",
        "provider": "Mistral AI",
        "headline": "12B general-purpose model with strong multilingual and tool-use support.",
        "summary": "Compact Mistral model designed for efficient local deployment with broad capabilities.",
        "description": (
            "Mistral Nemo is a 12B model co-developed with NVIDIA, optimised for local inference "
            "with strong multilingual support and function calling."
        ),
        "updatedLabel": "Updated 1 month ago",
        "popularityLabel": "650k downloads",
        "likesLabel": "128 likes",
        "badges": ["Multilingual", "Tool-use"],
        "capabilities": ["chat", "multilingual", "tool-use", "coding", "reasoning"],
        "defaultVariantId": "mistralai/Mistral-Nemo-Instruct-2407",
        "variants": [
            {
                "id": "mistralai/Mistral-Nemo-Instruct-2407",
                "name": "Mistral Nemo 12B Instruct",
                "repo": "mistralai/Mistral-Nemo-Instruct-2407",
                "link": "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
                "paramsB": 12.0,
                "sizeGb": 14.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "multilingual", "tool-use", "coding"],
                "note": "12B all-rounder with excellent multilingual and function calling support.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Mistral Nemo is a compact all-rounder with strong multilingual and tool-use support.",
            "Co-developed with NVIDIA for efficient local deployment.",
        ],
    },
]


def _flatten_catalog() -> list[dict[str, Any]]:
    flattened: list[dict[str, Any]] = []
    for family in MODEL_FAMILIES:
        for variant in family["variants"]:
            flattened.append(
                {
                    **variant,
                    "familyId": family["id"],
                    "familyName": family["name"],
                    "provider": family["provider"],
                }
            )
    return flattened


CATALOG: list[dict[str, Any]] = _flatten_catalog()
