from __future__ import annotations

from typing import Any


MODEL_FAMILIES: list[dict[str, Any]] = [
    {
        "id": "gemma-4",
        "name": "Gemma 4",
        "provider": "Google",
        "headline": "New multimodal Gemma family for reasoning, coding, and on-device workflows.",
        "summary": "Strong general-purpose family with compact edge variants and a larger A4B option for workstation-class use.",
        "description": (
            "Gemma 4 covers compact edge deployment through larger multimodal reasoning models. "
            "It is a good fit when you want a modern generalist with long context and strong coding support."
        ),
        "updatedLabel": "Updated 3 days ago",
        "popularityLabel": "323k downloads",
        "likesLabel": "58 likes",
        "badges": ["Staff pick", "Vision", "Reasoning"],
        "capabilities": ["reasoning", "vision", "coding", "multilingual"],
        "defaultVariantId": "google/gemma-4-26B-A4B-it",
        "variants": [
            {
                "id": "google/gemma-4-E4B-it",
                "name": "Gemma 4 E4B Instruct",
                "repo": "google/gemma-4-E4B-it",
                "link": "https://huggingface.co/google/gemma-4-E4B-it",
                "paramsB": 4.5,
                "sizeGb": 5.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["vision", "reasoning", "tool-use"],
                "note": "Compact Gemma 4 variant for laptops and small desktops.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "google/gemma-4-12B-it",
                "name": "Gemma 4 12B Instruct",
                "repo": "google/gemma-4-12B-it",
                "link": "https://huggingface.co/google/gemma-4-12B-it",
                "paramsB": 12.0,
                "sizeGb": 14.8,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["vision", "reasoning", "coding"],
                "note": "Higher quality Gemma 4 option for larger local rigs.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "google/gemma-4-26B-A4B-it",
                "name": "Gemma 4 26B A4B Instruct",
                "repo": "google/gemma-4-26B-A4B-it",
                "link": "https://huggingface.co/google/gemma-4-26B-A4B-it",
                "paramsB": 26.0,
                "sizeGb": 28.1,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["vision", "reasoning", "coding", "agents"],
                "note": "Large multimodal Gemma 4 variant for workstation-class setups.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "mlx-community/gemma-4-26b-a4b-it-5bit",
                "name": "Gemma 4 26B A4B MLX 5-bit",
                "repo": "mlx-community/gemma-4-26b-a4b-it-5bit",
                "link": "https://huggingface.co/mlx-community/gemma-4-26b-a4b-it-5bit",
                "paramsB": 26.0,
                "sizeGb": 18.5,
                "format": "MLX",
                "quantization": "5-bit",
                "capabilities": ["vision", "reasoning", "coding", "agents"],
                "note": "Community MLX conversion of the instruct checkpoint, with a bundled chat template for ready-to-run desktop chat.",
                "contextWindow": "256K",
                "launchMode": "direct",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Gemma 4 is built for reasoning, coding, and multimodal understanding.",
            "Small variants target local deployment; larger variants suit workstation-class hardware.",
            "Official transformer repos still route through conversion, while community MLX variants can run directly when available.",
        ],
    },
    {
        "id": "qwen-3-6",
        "name": "Qwen 3.6",
        "provider": "Qwen",
        "headline": "Latest Qwen release with agentic coding and repo-level reasoning upgrades.",
        "summary": "April 2026 successor to Qwen 3.5 with multi-token prediction and a new dense 27B variant alongside the MoE A3B line.",
        "description": (
            "Qwen 3.6 lands as a 27B dense model and a 35B MoE A3B variant, both Apache 2.0. "
            "262K native context (extensible to ~1M with YaRN), thinking-preservation across "
            "turns, and strong frontend / repository-level coding."
        ),
        "updatedLabel": "Released Apr 2026",
        "popularityLabel": "Featured family",
        "likesLabel": "Qwen official",
        "badges": ["Reasoning", "Coding", "Agents", "Long context"],
        # FU-072 (2026-05-28): restored ``vision``. FU-040 (2026-05-10)
        # had dropped it believing Qwen3.6 was text-only with vision on a
        # separate ``Qwen3.6-27B-VL`` we don't ship. Upstream has since
        # unified the family onto the multimodal ``Qwen3_5ForConditional
        # Generation`` arch — every Qwen3.6 config.json now carries
        # ``vision_config`` + ``image_token_id`` + ``vision_start/end``,
        # mlx-vlm ships ``qwen3_5`` / ``qwen3_5_moe`` model support, and
        # the ggml-org GGUF packs include an ``mmproj`` sibling. The base
        # model IS the VL now. The composer "Attach image" button stays
        # safe regardless: it reads the *runtime* ``supportsVision`` which
        # ``catalog/capabilities.py`` demotes to False for the MLX worker
        # (no image path) and gates on actual ``--mmproj`` resolution for
        # GGUF, so a vision badge never produces a broken button.
        "capabilities": ["reasoning", "coding", "vision", "tool-use"],
        "defaultVariantId": "Qwen/Qwen3.6-27B",
        "variants": [
            {
                "id": "Qwen/Qwen3.6-27B",
                "name": "Qwen3.6 27B",
                "repo": "Qwen/Qwen3.6-27B",
                "link": "https://huggingface.co/Qwen/Qwen3.6-27B",
                "paramsB": 27.0,
                "sizeGb": 54.0,
                "format": "Transformers",
                "quantization": "BF16",
                # FU-072: multimodal (vision_config present upstream).
                "capabilities": ["reasoning", "coding", "vision", "tool-use"],
                "note": "Dense 27B Qwen3.6 release with agentic coding tuning. Apache 2.0.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "Qwen/Qwen3.6-27B-FP8",
                "name": "Qwen3.6 27B FP8",
                "repo": "Qwen/Qwen3.6-27B-FP8",
                "link": "https://huggingface.co/Qwen/Qwen3.6-27B-FP8",
                "paramsB": 27.0,
                "sizeGb": 28.0,
                "format": "Transformers",
                "quantization": "FP8",
                # FU-072: multimodal (vision_config present upstream).
                "capabilities": ["reasoning", "coding", "vision", "tool-use"],
                "note": "FP8 quantization of the 27B dense release for ~30 GB VRAM systems.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "Qwen/Qwen3.6-35B-A3B",
                "name": "Qwen3.6 35B A3B",
                "repo": "Qwen/Qwen3.6-35B-A3B",
                "link": "https://huggingface.co/Qwen/Qwen3.6-35B-A3B",
                "paramsB": 35.0,
                "sizeGb": 70.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "vision", "agents", "tool-use"],
                "note": "MoE A3B variant — 35B total params, ~3B active per token. Apache 2.0.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "mlx-community/Qwen3.6-27B-4bit",
                "name": "Qwen3.6 27B MLX 4-bit",
                "repo": "mlx-community/Qwen3.6-27B-4bit",
                "link": "https://huggingface.co/mlx-community/Qwen3.6-27B-4bit",
                "paramsB": 27.0,
                "sizeGb": 15.5,
                "format": "MLX",
                "quantization": "4-bit",
                # FU-072: multimodal (vision_config present upstream).
                "capabilities": ["reasoning", "coding", "vision", "tool-use"],
                "note": "Community MLX 4-bit conversion for Apple Silicon — fastest local launch path.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "mlx-community/Qwen3.6-35B-A3B-4bit",
                "name": "Qwen3.6 35B A3B MLX 4-bit",
                "repo": "mlx-community/Qwen3.6-35B-A3B-4bit",
                "link": "https://huggingface.co/mlx-community/Qwen3.6-35B-A3B-4bit",
                "paramsB": 35.0,
                "sizeGb": 20.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["reasoning", "coding", "vision", "agents", "tool-use"],
                "note": "MoE 4-bit MLX conversion — sparse activation keeps memory close to a 4B model.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "lmstudio-community/Qwen3.6-27B-GGUF",
                "name": "Qwen3.6 27B GGUF",
                "repo": "lmstudio-community/Qwen3.6-27B-GGUF",
                "link": "https://huggingface.co/lmstudio-community/Qwen3.6-27B-GGUF",
                "paramsB": 27.0,
                "sizeGb": 16.5,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "coding", "vision", "tool-use"],
                "note": "Community GGUF pack quantized via llama.cpp b8883 for cross-platform llama.cpp runs.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-04",
            },
            {
                "id": "lmstudio-community/Qwen3.6-35B-A3B-GGUF",
                "name": "Qwen3.6 35B A3B GGUF",
                "repo": "lmstudio-community/Qwen3.6-35B-A3B-GGUF",
                "link": "https://huggingface.co/lmstudio-community/Qwen3.6-35B-A3B-GGUF",
                "paramsB": 35.0,
                "sizeGb": 21.0,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "coding", "vision", "agents", "tool-use"],
                "note": "MoE GGUF (llama.cpp b8814) — runs the 35B sparse model through standard llama-server.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-04",
            },
            {
                # FU-047 (PR #22673 merged 2026-05-16): GGUF mirror with
                # baked-in MTP heads. Enables native --spec-type draft-mtp
                # speculative decoding on any llama.cpp build that
                # advertises --spec-type. Q8_0 is the recommended quant per
                # the PR (BF16 also shipped but ~2x disk + RAM).
                "id": "ggml-org/Qwen3.6-27B-MTP-GGUF",
                "name": "Qwen3.6 27B MTP GGUF",
                "repo": "ggml-org/Qwen3.6-27B-MTP-GGUF",
                "link": "https://huggingface.co/ggml-org/Qwen3.6-27B-MTP-GGUF",
                "paramsB": 27.0,
                "sizeGb": 29.0,
                "format": "GGUF",
                "quantization": "Q8_0",
                "capabilities": ["reasoning", "coding", "vision", "tool-use"],
                "note": "Baked-in MTP heads + mmproj sibling for vision. Pair with --spec-type draft-mtp for 1.8-2.2x speedup with zero quality loss.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-05",
            },
            {
                "id": "ggml-org/Qwen3.6-35B-A3B-MTP-GGUF",
                "name": "Qwen3.6 35B A3B MTP GGUF",
                "repo": "ggml-org/Qwen3.6-35B-A3B-MTP-GGUF",
                "link": "https://huggingface.co/ggml-org/Qwen3.6-35B-A3B-MTP-GGUF",
                "paramsB": 35.0,
                "sizeGb": 37.0,
                "format": "GGUF",
                "quantization": "Q8_0",
                "capabilities": ["reasoning", "coding", "vision", "agents", "tool-use"],
                "note": "MoE with baked-in MTP heads + mmproj sibling for vision. --spec-type draft-mtp speedup compounds with the sparse activation savings.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-05",
            },
            {
                # FU-064: ggml-org canonical non-MTP companion (2026-05-22).
                # Same Q8_0 quality bar as the MTP variant but without the
                # baked-in MTP heads — for users on llama.cpp builds that
                # predate PR #22673 or who don't want speculative decoding.
                "id": "ggml-org/Qwen3.6-27B-GGUF",
                "name": "Qwen3.6 27B GGUF (ggml-org Q8_0)",
                "repo": "ggml-org/Qwen3.6-27B-GGUF",
                "link": "https://huggingface.co/ggml-org/Qwen3.6-27B-GGUF",
                "paramsB": 27.0,
                "sizeGb": 29.0,
                "format": "GGUF",
                "quantization": "Q8_0",
                "capabilities": ["reasoning", "coding", "vision", "tool-use"],
                "note": "ggml-org canonical Q8_0 pack + mmproj sibling for vision. No MTP heads — pick the -MTP-GGUF sibling for speculative decoding.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-05",
            },
            {
                "id": "ggml-org/Qwen3.6-35B-A3B-GGUF",
                "name": "Qwen3.6 35B A3B GGUF (ggml-org Q8_0)",
                "repo": "ggml-org/Qwen3.6-35B-A3B-GGUF",
                "link": "https://huggingface.co/ggml-org/Qwen3.6-35B-A3B-GGUF",
                "paramsB": 35.0,
                "sizeGb": 37.0,
                "format": "GGUF",
                "quantization": "Q8_0",
                "capabilities": ["reasoning", "coding", "vision", "agents", "tool-use"],
                "note": "ggml-org canonical Q8_0 MoE pack + mmproj sibling for vision. No MTP heads — pick the -MTP-GGUF sibling for speculative decoding.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-05",
            },
        ],
        "readme": [
            "Qwen 3.6 is the April 2026 follow-up to Qwen 3.5, with two open-weight releases: a dense 27B and a 35B-A3B MoE.",
            "Both target agentic coding, repository-level reasoning, and thinking-preservation across multi-turn dialogues.",
            "Native 262K context extends to ~1M tokens via YaRN; mlx-community and lmstudio-community already publish MLX 4-bit and GGUF Q4_K_M variants.",
        ],
    },
    {
        "id": "qwen-3-5",
        "name": "Qwen 3.5",
        "provider": "Qwen",
        "headline": "Hybrid reasoning family with long context and strong agent support.",
        "summary": "Useful when you want modern reasoning and coding performance with a wide spread of model sizes.",
        "description": (
            "Qwen 3.5 spans compact and MoE-heavy variants with long context support. "
            "It fits well for agent-style workflows, tool use, and coding-heavy chats."
        ),
        "updatedLabel": "Updated this month",
        "popularityLabel": "Featured family",
        "likesLabel": "Qwen official",
        "badges": ["Reasoning", "Coding", "Long context"],
        # FU-072: Qwen3.5 is multimodal upstream (Qwen3_5ForConditional
        # Generation + vision_config; mlx-vlm ships qwen3_5 support).
        # FU-040 had marked the family text-only — now corrected. The
        # runtime ``supportsVision`` is still demoted per-engine in
        # catalog/capabilities.py (MLX worker carries no images; GGUF
        # gates on mmproj), so the family vision tag drives badges only,
        # never a broken composer button.
        "capabilities": ["reasoning", "coding", "vision", "tool-use"],
        "defaultVariantId": "Qwen/Qwen3.5-9B",
        "variants": [
            {
                "id": "Qwen/Qwen3.5-4B",
                "name": "Qwen3.5 4B",
                "repo": "Qwen/Qwen3.5-4B",
                "link": "https://huggingface.co/Qwen/Qwen3.5-4B",
                "paramsB": 4.0,
                "sizeGb": 5.1,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "vision", "video", "tool-use"],
                "note": "Smaller Qwen 3.5 variant with strong utility for everyday local work. Multimodal (image + video) like its 9B sibling.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen3.5-9B",
                "name": "Qwen3.5 9B",
                "repo": "Qwen/Qwen3.5-9B",
                "link": "https://huggingface.co/Qwen/Qwen3.5-9B",
                "paramsB": 9.0,
                "sizeGb": 10.9,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "vision", "video", "tool-use"],
                "note": "Balanced Qwen 3.5 option for serious local chat, code, and agent tasks.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "mlx-community/Qwen3.5-9B-4bit",
                "name": "Qwen3.5 9B MLX 4-bit",
                "repo": "mlx-community/Qwen3.5-9B-4bit",
                "link": "https://huggingface.co/mlx-community/Qwen3.5-9B-4bit",
                "paramsB": 9.0,
                "sizeGb": 6.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["reasoning", "coding", "vision", "video", "tool-use"],
                "note": "Community MLX conversion for Apple Silicon with a much quicker local launch path.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "mlx",
            },
            {
                "id": "lmstudio-community/Qwen3.5-9B-GGUF",
                "name": "Qwen3.5 9B GGUF",
                "repo": "lmstudio-community/Qwen3.5-9B-GGUF",
                "link": "https://huggingface.co/lmstudio-community/Qwen3.5-9B-GGUF",
                "paramsB": 9.0,
                "sizeGb": 5.8,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "coding", "vision", "video", "tool-use"],
                "note": "Community GGUF pack with ready-made quantizations for quick llama.cpp runs. Vision needs the mmproj sibling on disk.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
            {
                "id": "Qwen/Qwen3.5-35B-A3B-FP8",
                "name": "Qwen3.5 35B A3B",
                "repo": "Qwen/Qwen3.5-35B-A3B-FP8",
                "link": "https://huggingface.co/Qwen/Qwen3.5-35B-A3B-FP8",
                "paramsB": 35.0,
                "sizeGb": 22.8,
                "format": "Transformers",
                "quantization": "FP8",
                "capabilities": ["reasoning", "coding", "vision", "agents"],
                "note": "Sparse MoE-style Qwen 3.5 variant tuned for high-end local or server workflows.",
                "contextWindow": "262K",
                "launchMode": "convert",
                "backend": "mlx",
            },
        ],
        "readme": [
            "Qwen 3.5 is a reasoning-first family with long context and strong coding support.",
            "Thinking mode is model-native, so it works well for agent-style threads and tool-rich prompts.",
            "The catalog now mixes official transformer repos with community GGUF and MLX variants so you can go straight to a runnable format when one exists.",
        ],
    },
    {
        "id": "nemotron-3-nano",
        "name": "Nemotron 3 Nano",
        "provider": "NVIDIA",
        "headline": "Compact reasoning-first family aimed at efficient local deployment.",
        "summary": "Good fit when you want a modern small model that still feels capable in chat and tool use.",
        "description": (
            "Nemotron 3 Nano focuses on local efficiency and reasoning utility. "
            "The GGUF variant is ready to use directly in the local llama.cpp path, while the BF16 weights can feed conversion workflows."
        ),
        "updatedLabel": "Updated 2 weeks ago",
        "popularityLabel": "New release",
        "likesLabel": "NVIDIA official",
        "badges": ["Popular", "Reasoning", "Local-first"],
        "capabilities": ["reasoning", "tool-use", "chat"],
        "defaultVariantId": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
        "variants": [
            {
                "id": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
                "name": "Nemotron 3 Nano 4B GGUF",
                "repo": "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
                "link": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
                "paramsB": 4.0,
                "sizeGb": 3.1,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "chat", "tool-use"],
                "note": "Direct-load GGUF path for fast local trials and thread switching.",
                "contextWindow": "128K",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
            {
                "id": "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
                "name": "Nemotron 3 Nano 4B BF16",
                "repo": "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
                "link": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
                "paramsB": 4.0,
                "sizeGb": 8.2,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "chat", "tool-use"],
                "note": "Official BF16 weights if you want to convert into an MLX-friendly local artifact.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
                "name": "Nemotron 3 Nano 30B A3B FP8",
                "repo": "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
                "link": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
                "paramsB": 30.0,
                "sizeGb": 35.0,
                "format": "Transformers",
                "quantization": "FP8",
                "capabilities": ["reasoning", "thinking", "tool-use", "coding", "agents"],
                "note": "Larger official Nemotron 3 Nano checkpoint with configurable reasoning traces and very long context.",
                "contextWindow": "1M",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
                "name": "Nemotron 3 Nano 30B A3B GGUF",
                "repo": "lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
                "link": "https://huggingface.co/lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
                "paramsB": 30.0,
                "sizeGb": 24.5,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "thinking", "tool-use", "coding", "agents"],
                "note": "Community GGUF conversion for the larger Nemotron 3 Nano release when you want a ready llama.cpp path.",
                "contextWindow": "1M",
                "launchMode": "direct",
                "backend": "llama.cpp",
            },
        ],
        "readme": [
            "Nemotron 3 Nano is built for compact local deployments without falling back to obviously weak outputs.",
            "The family now includes both the smaller 4B checkpoints and the newer 30B A3B release.",
            "Official checkpoints remain available for conversion, while community GGUF packs give you a direct runtime path.",
        ],
    },
    {
        "id": "devstral-small",
        "name": "Devstral Small",
        "provider": "Mistral AI",
        "headline": "Agentic coding model family tuned for software engineering tasks.",
        "summary": "Best when the conversation is code-heavy and you want a thread-specific model for repo work.",
        "description": (
            "Devstral focuses on software engineering workflows and tool-using assistants. "
            "The GGUF release is directly usable, and the BF16 release can feed conversion-oriented setups."
        ),
        "updatedLabel": "Updated 3 weeks ago",
        "popularityLabel": "Trending with coding users",
        "likesLabel": "Mistral official",
        "badges": ["Coding", "Agents", "Tool use"],
        "capabilities": ["coding", "agents", "tool-use"],
        "defaultVariantId": "mistralai/Devstral-Small-2507_gguf",
        "variants": [
            {
                "id": "mistralai/Devstral-Small-2507_gguf",
                "name": "Devstral Small 2507 GGUF",
                "repo": "mistralai/Devstral-Small-2507_gguf",
                "link": "https://huggingface.co/mistralai/Devstral-Small-2507_gguf",
                "paramsB": 24.0,
                "sizeGb": 15.7,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["coding", "agents", "tool-use"],
                "note": "Direct GGUF path for local coding threads and repo-centric workflows.",
                "contextWindow": "128K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2025-07",
            },
            {
                "id": "mistralai/Devstral-Small-2507",
                "name": "Devstral Small 2507 BF16",
                "repo": "mistralai/Devstral-Small-2507",
                "link": "https://huggingface.co/mistralai/Devstral-Small-2507",
                "paramsB": 24.0,
                "sizeGb": 29.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["coding", "agents", "tool-use"],
                "note": "Official BF16 weights for conversion-oriented local setups.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2025-07",
            },
        ],
        "readme": [
            "Devstral is tuned for software engineering and tool-using workflows.",
            "Use the GGUF variant when you want the quickest path into local code threads.",
            "Use the BF16 repo when you want to convert into an MLX artifact instead of running GGUF.",
        ],
    },
    {
        "id": "qwen3-coder",
        "name": "Qwen3 Coder",
        "provider": "Qwen",
        "headline": "Code-specialised Qwen3 with strong agentic and tool-use support.",
        "summary": "Large official coding checkpoint with BF16 and FP8 repos for high-end local and server workflows.",
        "description": (
            "Qwen3 Coder is optimised for software engineering workflows with agentic tool use, "
            "large context windows, and configurable thinking depth. Great for local coding assistants."
        ),
        "updatedLabel": "Updated Feb 2026",
        "popularityLabel": "639k downloads",
        "likesLabel": "1.3k likes",
        "badges": ["Coding", "Agents", "Tool-use"],
        "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
        "defaultVariantId": "Qwen/Qwen3-Coder-Next-FP8",
        "variants": [
            {
                "id": "Qwen/Qwen3-Coder-Next",
                "name": "Qwen3 Coder Next BF16",
                "repo": "Qwen/Qwen3-Coder-Next",
                "link": "https://huggingface.co/Qwen/Qwen3-Coder-Next",
                "paramsB": 75.0,
                "sizeGb": 148.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
                "note": "Full official Qwen3 Coder Next checkpoint for very high-memory workstations and servers.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            {
                "id": "Qwen/Qwen3-Coder-Next-FP8",
                "name": "Qwen3 Coder Next FP8",
                "repo": "Qwen/Qwen3-Coder-Next-FP8",
                "link": "https://huggingface.co/Qwen/Qwen3-Coder-Next-FP8",
                "paramsB": 75.0,
                "sizeGb": 74.9,
                "format": "Transformers",
                "quantization": "FP8",
                "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
                "note": "Smaller official FP8 repo for the same Qwen3 Coder Next family when you want the lighter download.",
                "contextWindow": "256K",
                "launchMode": "convert",
                "backend": "mlx",
            },
            # FU-041 (2026-05-10): community MLX 4-bit conversion of the
            # Qwen3-Next architecture (qwen3_next, sparse MoE w/ 512
            # experts, ~3B active per token, hidden_size=2048). Without
            # this variant the library matcher in src/utils/library.ts
            # fuzzy-matched a local ``Qwen3-Coder-Next-MLX-4bit`` install
            # to the unrelated ``mlx-community/Qwen3.6-27B-4bit`` (dense
            # 27B Coder, completely different arch — hidden_size=5120,
            # no MoE), which then surfaced the wrong canonicalRepo into
            # the runtime snapshot, picked up the wrong capability set,
            # and routed DFlash lookups to the wrong drafter. Adding the
            # variant explicitly lets the matcher score 80+ on an exact
            # repo-path substring hit instead of falling back to the
            # closest-quant-and-format match.
            {
                "id": "lmstudio-community/Qwen3-Coder-Next-MLX-4bit",
                "name": "Qwen3 Coder Next MLX 4-bit",
                "repo": "lmstudio-community/Qwen3-Coder-Next-MLX-4bit",
                "link": "https://huggingface.co/lmstudio-community/Qwen3-Coder-Next-MLX-4bit",
                # 80B total params, ~3B active per token; the on-disk
                # 4-bit conversion fits ~45 GB.
                "paramsB": 80.0,
                "sizeGb": 45.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["coding", "agents", "tool-use", "reasoning", "thinking"],
                "note": "Community MLX 4-bit conversion of the Qwen3-Next MoE coder for Apple Silicon — fastest local launch path.",
                "contextWindow": "262K",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
        ],
        "readme": [
            "Qwen3 Coder Next is purpose-built for software engineering with function calling and agentic workflows.",
            "Choose the FP8 repo when you want the lighter official download; choose BF16 when you want the full checkpoint.",
            "These official Next repos replace the older provisional 8B and 32B catalog placeholders.",
        ],
    },
    {
        "id": "qwen-2-5",
        "name": "Qwen 2.5",
        "provider": "Qwen",
        "headline": "Versatile general-purpose family with chat, coding, and multilingual variants.",
        "summary": "Mature, well-tested family spanning 0.5B to 72B with strong community support.",
        "description": (
            "Qwen 2.5 is a proven workhorse family that covers everything from tiny edge models "
            "to large multilingual reasoners. Excellent GGUF availability in the community."
        ),
        "updatedLabel": "Updated 2 weeks ago",
        "popularityLabel": "890k downloads",
        "likesLabel": "156 likes",
        "badges": ["Popular", "Coding", "Multilingual"],
        "capabilities": ["chat", "coding", "multilingual", "reasoning", "tool-use"],
        "defaultVariantId": "Qwen/Qwen2.5-7B-Instruct",
        "variants": [
            {
                "id": "Qwen/Qwen2.5-3B-Instruct",
                "name": "Qwen 2.5 3B Instruct",
                "repo": "Qwen/Qwen2.5-3B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct",
                "paramsB": 3.0,
                "sizeGb": 3.6,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "coding", "multilingual"],
                "note": "Ultra-compact variant for quick prototyping and edge deployments.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-09",
            },
            {
                "id": "Qwen/Qwen2.5-7B-Instruct",
                "name": "Qwen 2.5 7B Instruct",
                "repo": "Qwen/Qwen2.5-7B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
                "paramsB": 7.0,
                "sizeGb": 8.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "coding", "reasoning", "multilingual"],
                "note": "Well-rounded 7B for general chat and coding on 16GB+ machines.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-09",
            },
            {
                "id": "Qwen/Qwen2.5-Coder-7B-Instruct",
                "name": "Qwen 2.5 Coder 7B",
                "repo": "Qwen/Qwen2.5-Coder-7B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
                "paramsB": 7.0,
                "sizeGb": 8.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["coding", "tool-use", "agents"],
                "note": "Code-focused 7B with function calling and agentic support.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-11",
            },
            {
                "id": "Qwen/Qwen2.5-32B-Instruct",
                "name": "Qwen 2.5 32B Instruct",
                "repo": "Qwen/Qwen2.5-32B-Instruct",
                "link": "https://huggingface.co/Qwen/Qwen2.5-32B-Instruct",
                "paramsB": 32.0,
                "sizeGb": 38.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "coding", "reasoning", "multilingual", "tool-use"],
                "note": "Large Qwen 2.5 for workstation setups needing quality and breadth.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-09",
            },
        ],
        "readme": [
            "Qwen 2.5 is a mature, well-supported family with extensive community GGUF availability.",
            "The Coder variant is specialised for software engineering and function calling.",
        ],
    },
    {
        "id": "llama-3-3",
        "name": "Llama 3.3",
        "provider": "Meta",
        "headline": "Meta's flagship open-weight model with strong reasoning and multilingual support.",
        "summary": "High-quality 70B distilled into efficient variants. Industry standard for local inference.",
        "description": (
            "Llama 3.3 brings Meta's strongest open-weight reasoning to local hardware. "
            "The 70B is the gold standard; community quantisations make it accessible on Apple Silicon."
        ),
        "updatedLabel": "Updated 3 weeks ago",
        "popularityLabel": "1.2M downloads",
        "likesLabel": "312 likes",
        "badges": ["Popular", "Reasoning", "Multilingual"],
        "capabilities": ["chat", "reasoning", "coding", "multilingual", "tool-use"],
        "defaultVariantId": "meta-llama/Llama-3.3-70B-Instruct",
        "variants": [
            {
                "id": "meta-llama/Llama-3.3-70B-Instruct",
                "name": "Llama 3.3 70B Instruct",
                "repo": "meta-llama/Llama-3.3-70B-Instruct",
                "link": "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
                "paramsB": 70.0,
                "sizeGb": 84.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "reasoning", "coding", "multilingual", "tool-use"],
                "note": "Full 70B for 128GB+ machines. Highest quality open-weight reasoning.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-12",
            },
            {
                "id": "mlx-community/Llama-3.3-70B-Instruct-4bit",
                "name": "Llama 3.3 70B MLX 4-bit",
                "repo": "mlx-community/Llama-3.3-70B-Instruct-4bit",
                "link": "https://huggingface.co/mlx-community/Llama-3.3-70B-Instruct-4bit",
                "paramsB": 70.0,
                "sizeGb": 40.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["chat", "reasoning", "coding", "multilingual", "tool-use"],
                "note": "4-bit quantisation for 64GB machines. Good quality/size tradeoff.",
                "contextWindow": "128K",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2024-12",
            },
        ],
        "readme": [
            "Llama 3.3 is Meta's strongest open-weight model, widely used as a benchmark.",
            "The 4-bit MLX variant fits on 64GB Apple Silicon with room for context.",
        ],
    },
    {
        "id": "phi-4",
        "name": "Phi 4",
        "provider": "Microsoft",
        "headline": "Compact reasoning models with strong STEM and coding performance.",
        "summary": "Small-but-capable family that punches above its weight on reasoning benchmarks.",
        "description": (
            "Phi 4 delivers impressive reasoning and STEM performance in compact sizes. "
            "Great for resource-constrained setups that need quality reasoning."
        ),
        "updatedLabel": "Updated 2 weeks ago",
        "popularityLabel": "420k downloads",
        "likesLabel": "89 likes",
        "badges": ["Reasoning", "Compact", "STEM"],
        "capabilities": ["reasoning", "coding", "chat", "multilingual"],
        "defaultVariantId": "microsoft/phi-4",
        "variants": [
            {
                "id": "microsoft/phi-4",
                "name": "Phi 4 14B",
                "repo": "microsoft/phi-4",
                "link": "https://huggingface.co/microsoft/phi-4",
                "paramsB": 14.0,
                "sizeGb": 16.8,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "chat"],
                "note": "14B model that rivals much larger models on STEM and reasoning tasks.",
                "contextWindow": "16K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-12",
            },
            {
                "id": "mlx-community/phi-4-4bit",
                "name": "Phi 4 14B MLX 4-bit",
                "repo": "mlx-community/phi-4-4bit",
                "link": "https://huggingface.co/mlx-community/phi-4-4bit",
                "paramsB": 14.0,
                "sizeGb": 8.5,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["reasoning", "coding", "chat"],
                "note": "Compact 4-bit variant that runs well on 16GB machines.",
                "contextWindow": "16K",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2025-01",
            },
        ],
        "readme": [
            "Phi 4 punches above its weight on reasoning and STEM benchmarks.",
            "The 4-bit MLX variant is one of the best options for 16GB MacBooks.",
        ],
    },
    {
        "id": "mistral-nemo",
        "name": "Mistral Nemo",
        "provider": "Mistral AI",
        "headline": "12B general-purpose model with strong multilingual and tool-use support.",
        "summary": "Compact Mistral model designed for efficient local deployment with broad capabilities.",
        "description": (
            "Mistral Nemo is a 12B model co-developed with NVIDIA, optimised for local inference "
            "with strong multilingual support and function calling."
        ),
        "updatedLabel": "Updated 1 month ago",
        "popularityLabel": "650k downloads",
        "likesLabel": "128 likes",
        "badges": ["Multilingual", "Tool-use"],
        "capabilities": ["chat", "multilingual", "tool-use", "coding", "reasoning"],
        "defaultVariantId": "mistralai/Mistral-Nemo-Instruct-2407",
        "variants": [
            {
                "id": "mistralai/Mistral-Nemo-Instruct-2407",
                "name": "Mistral Nemo 12B Instruct",
                "repo": "mistralai/Mistral-Nemo-Instruct-2407",
                "link": "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
                "paramsB": 12.0,
                "sizeGb": 14.4,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["chat", "multilingual", "tool-use", "coding"],
                "note": "12B all-rounder with excellent multilingual and function calling support.",
                "contextWindow": "128K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2024-07",
            },
        ],
        "readme": [
            "Mistral Nemo is a compact all-rounder with strong multilingual and tool-use support.",
            "Co-developed with NVIDIA for efficient local deployment.",
        ],
    },
    {
        # Frontier sparse-MoE family (DeepseekV4ForCausalLM, 256 routed experts
        # / 6 active, 1M context via YaRN, baked-in MTP head -> speculative
        # decoding). Text-only. Listed for discovery awareness — even the
        # "small" Flash variant is 154 GB at 4-bit, so these target top-end
        # desktops / workstations, not laptops.
        "id": "deepseek-v4",
        "name": "DeepSeek V4",
        "provider": "DeepSeek",
        "headline": "Frontier MoE reasoning + agentic coding; the Flash variant is the local-viable one.",
        "summary": "DeepSeek V4 — Flash (284B / ~13B active) for top-end desktops, Pro (1.6T) for the frontier.",
        "description": (
            "DeepSeek V4 is a sparse Mixture-of-Experts family (256 routed experts, ~6 active per token) "
            "with 1M-token context via YaRN and a baked-in MTP head for speculative decoding. V4-Flash "
            "activates ~13B of 284B total parameters; V4-Pro is the 1.6T flagship. Text-only, MIT-licensed."
        ),
        "updatedLabel": "Released 2026",
        "popularityLabel": "Frontier family",
        "likesLabel": "DeepSeek official",
        "badges": ["Reasoning", "Coding", "Agents", "Long context"],
        "capabilities": ["reasoning", "coding", "agents", "tool-use"],
        "defaultVariantId": "mlx-community/DeepSeek-V4-Flash-4bit",
        "variants": [
            {
                "id": "mlx-community/DeepSeek-V4-Flash-4bit",
                "name": "DeepSeek V4 Flash MLX 4-bit",
                "repo": "mlx-community/DeepSeek-V4-Flash-4bit",
                "link": "https://huggingface.co/mlx-community/DeepSeek-V4-Flash-4bit",
                "paramsB": 284.0,
                "sizeGb": 154.0,
                "format": "MLX",
                "quantization": "4-bit",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "MoE 284B / ~13B active. 4-bit MLX needs ~160 GB unified memory (M3/M4 Ultra). MTP head enables speculative decoding.",
                "contextWindow": "1M",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "mlx-community/DeepSeek-V4-Flash-8bit",
                "name": "DeepSeek V4 Flash MLX 8-bit",
                "repo": "mlx-community/DeepSeek-V4-Flash-8bit",
                "link": "https://huggingface.co/mlx-community/DeepSeek-V4-Flash-8bit",
                "paramsB": 284.0,
                "sizeGb": 284.0,
                "format": "MLX",
                "quantization": "8-bit",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "8-bit MLX conversion — higher fidelity, ~290 GB unified memory.",
                "contextWindow": "1M",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "deepseek-ai/DeepSeek-V4-Flash",
                "name": "DeepSeek V4 Flash (BF16)",
                "repo": "deepseek-ai/DeepSeek-V4-Flash",
                "link": "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash",
                "paramsB": 284.0,
                "sizeGb": 568.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "Official BF16 weights — convert to MLX/GGUF locally or run on a multi-GPU box.",
                "contextWindow": "1M",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
            {
                "id": "deepseek-ai/DeepSeek-V4-Pro",
                "name": "DeepSeek V4 Pro (frontier)",
                "repo": "deepseek-ai/DeepSeek-V4-Pro",
                "link": "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro",
                "paramsB": 1600.0,
                "sizeGb": 3200.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "1.6T flagship (~49B active). Frontier / awareness — needs a GPU cluster; not a local launch path.",
                "contextWindow": "1M",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
        ],
        "readme": [
            "DeepSeek V4 is a sparse-MoE family with 1M-token context and baked-in MTP heads for speculative decoding.",
            "V4-Flash (284B / ~13B active) is the local-viable variant: the mlx-community 4-bit conversion is ~154 GB and runs on M3/M4 Ultra-class unified memory.",
            "V4-Pro (1.6T) is listed for awareness; it targets multi-GPU clusters rather than a single desktop.",
        ],
    },
    {
        # Frontier sparse-MoE family (GlmMoeDsa arch, 256 routed experts / 8
        # active, ~200K context). Text-only. Z.ai / Tsinghua. Listed for
        # discovery awareness — even 4-bit GGUF is ~515 GB, so this is a
        # cluster / very-high-end-workstation family, not a laptop one.
        "id": "glm-5",
        "name": "GLM-5",
        "provider": "Z.ai",
        "headline": "Z.ai / Tsinghua frontier MoE — agentic coding rivaling closed frontier models.",
        "summary": "GLM-5 / GLM-5.1 sparse MoE (256 experts), ~200K context. Frontier-scale — top-end hardware only.",
        "description": (
            "GLM-5 is a large sparse Mixture-of-Experts model (GlmMoeDsa architecture, 256 routed experts, "
            "8 active per token) with ~200K context. GLM-5.1 is the refined release. Strong agentic coding "
            "and reasoning. Text-only, open weights — frontier-scale, so even a 4-bit GGUF is ~500 GB."
        ),
        "updatedLabel": "Released 2026",
        "popularityLabel": "Frontier family",
        "likesLabel": "Z.ai official",
        "badges": ["Coding", "Reasoning", "Agents", "Long context"],
        "capabilities": ["reasoning", "coding", "agents", "tool-use"],
        "defaultVariantId": "unsloth/GLM-5.1-GGUF",
        "variants": [
            {
                "id": "unsloth/GLM-5.1-GGUF",
                "name": "GLM-5.1 GGUF",
                "repo": "unsloth/GLM-5.1-GGUF",
                "link": "https://huggingface.co/unsloth/GLM-5.1-GGUF",
                "paramsB": 735.0,
                "sizeGb": 515.0,
                "format": "GGUF",
                "quantization": "Q4_K_M",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "Q4_K_M ~515 GB; the same repo ships smaller UD-IQ2 quants down to ~250 GB. Frontier-scale llama.cpp run.",
                "contextWindow": "200K",
                "launchMode": "direct",
                "backend": "llama.cpp",
                "releaseDate": "2026-05",
            },
            {
                "id": "mlx-community/GLM-5.1-MXFP4-Q8",
                "name": "GLM-5.1 MLX MXFP4",
                "repo": "mlx-community/GLM-5.1-MXFP4-Q8",
                "link": "https://huggingface.co/mlx-community/GLM-5.1-MXFP4-Q8",
                "paramsB": 735.0,
                "sizeGb": 449.0,
                "format": "MLX",
                "quantization": "MXFP4",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "MXFP4 MoE quant for Apple Silicon — ~450 GB unified memory.",
                "contextWindow": "200K",
                "launchMode": "direct",
                "backend": "mlx",
                "releaseDate": "2026-05",
            },
            {
                "id": "zai-org/GLM-5.1",
                "name": "GLM-5.1 (BF16)",
                "repo": "zai-org/GLM-5.1",
                "link": "https://huggingface.co/zai-org/GLM-5.1",
                "paramsB": 735.0,
                "sizeGb": 1507.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "Official BF16 weights — convert / quantize locally or run on a multi-GPU box.",
                "contextWindow": "200K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-05",
            },
            {
                "id": "zai-org/GLM-5",
                "name": "GLM-5 (BF16)",
                "repo": "zai-org/GLM-5",
                "link": "https://huggingface.co/zai-org/GLM-5",
                "paramsB": 735.0,
                "sizeGb": 1507.0,
                "format": "Transformers",
                "quantization": "BF16",
                "capabilities": ["reasoning", "coding", "agents", "tool-use"],
                "note": "Initial GLM-5 release; GLM-5.1 is the refined follow-up — prefer it unless reproducing a baseline.",
                "contextWindow": "200K",
                "launchMode": "convert",
                "backend": "mlx",
                "releaseDate": "2026-04",
            },
        ],
        "readme": [
            "GLM-5 is Z.ai / Tsinghua's frontier sparse-MoE family (GlmMoeDsa, 256 experts / 8 active), strong on agentic coding.",
            "GLM-5.1 is the refined release; unsloth + mlx-community publish GGUF and MXFP4 quants.",
            "Frontier-scale: a 4-bit GGUF is ~515 GB, so this family targets clusters and very-high-end workstations.",
        ],
    },
]


def _flatten_catalog() -> list[dict[str, Any]]:
    flattened: list[dict[str, Any]] = []
    for family in MODEL_FAMILIES:
        for variant in family["variants"]:
            flattened.append(
                {
                    **variant,
                    "familyId": family["id"],
                    "familyName": family["name"],
                    "provider": family["provider"],
                }
            )
    return flattened


CATALOG: list[dict[str, Any]] = _flatten_catalog()
