/**
 * Test-only fixtures. NOT imported by production code.
 * Production hooks use empty defaults from src/defaults.ts instead.
 */
import type {
  ImageGenerationPayload,
  ImageModelFamily,
  ImageOutputArtifact,
  WorkspaceData,
} from "./types";

function stableImageHash(value: string) {
  let acc = 0;
  for (let index = 0; index < value.length; index += 1) {
    acc = (acc + value.charCodeAt(index) * (index + 17)) % 0xffffff;
  }
  return acc;
}

function placeholderImageDataUrl(prompt: string, modelName: string, width: number, height: number, seed: number) {
  const hash = stableImageHash(`${modelName}:${prompt}:${seed}`);
  const hueA = hash % 360;
  const hueB = (hash * 7) % 360;
  const accentX = 90 + (hash % 240);
  const accentY = 80 + ((hash >> 3) % 200);
  const promptLine = prompt.trim() || "Generated image preview";
  const safePrompt = promptLine.replace(/[&<>"]/g, (match) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    "\"": "&quot;",
  }[match] ?? match));
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
      <defs>
        <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="hsl(${hueA} 72% 58%)" />
          <stop offset="100%" stop-color="hsl(${hueB} 68% 46%)" />
        </linearGradient>
      </defs>
      <rect width="${width}" height="${height}" rx="28" fill="url(#bg)" />
      <circle cx="${accentX}" cy="${accentY}" r="${Math.max(42, Math.round(width * 0.12))}" fill="rgba(255,255,255,0.18)" />
      <circle cx="${width - accentX}" cy="${height - accentY}" r="${Math.max(36, Math.round(width * 0.09))}" fill="rgba(8,12,20,0.18)" />
      <rect x="28" y="${height - 136}" width="${Math.max(240, width - 56)}" height="108" rx="24" fill="rgba(11,15,22,0.38)" stroke="rgba(255,255,255,0.14)" />
      <text x="52" y="${height - 90}" fill="white" font-size="28" font-family="SF Pro Display, Inter, sans-serif" font-weight="700">${modelName}</text>
      <text x="52" y="${height - 52}" fill="rgba(255,255,255,0.88)" font-size="19" font-family="SF Pro Text, Inter, sans-serif">${safePrompt.slice(0, 72)}</text>
    </svg>
  `.trim();
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

export const mockImageCatalog: ImageModelFamily[] = [
  {
    id: "flux-fast",
    name: "FLUX.1 Schnell",
    provider: "Black Forest Labs",
    headline: "Fast prompt-to-image path for quick concepting and moodboards.",
    summary: "Best starter option for rapid local ideation when you care more about speed and iteration than maximum fidelity.",
    updatedLabel: "Curated starter pick",
    badges: ["Fast", "General", "Photoreal"],
    defaultVariantId: "black-forest-labs/FLUX.1-schnell",
    variants: [
      {
        id: "black-forest-labs/FLUX.1-schnell",
        familyId: "flux-fast",
        name: "FLUX.1 Schnell",
        provider: "Black Forest Labs",
        repo: "black-forest-labs/FLUX.1-schnell",
        link: "https://huggingface.co/black-forest-labs/FLUX.1-schnell",
        runtime: "Stub diffusion pipeline",
        styleTags: ["photoreal", "general", "fast"],
        taskSupport: ["txt2img"],
        sizeGb: 23.7,
        recommendedResolution: "1024×1024",
        note: "Designed as the quick-start option for the first image tab slice.",
        availableLocally: true,
        estimatedGenerationSeconds: 4.2,
        lastModified: "2025-01-09T00:00:00Z",
      },
    ],
  },
  {
    id: "flux-dev",
    name: "FLUX.1 Dev",
    provider: "Black Forest Labs",
    headline: "High-fidelity guidance-distilled model for detailed, prompt-faithful generation.",
    summary: "Balanced option for the eventual production runtime when you want stronger final image quality than the fast path.",
    updatedLabel: "Curated quality pick",
    badges: ["Balanced", "General", "Detailed"],
    defaultVariantId: "black-forest-labs/FLUX.1-dev",
    variants: [
      {
        id: "black-forest-labs/FLUX.1-dev",
        familyId: "flux-dev",
        name: "FLUX.1 Dev",
        provider: "Black Forest Labs",
        repo: "black-forest-labs/FLUX.1-dev",
        link: "https://huggingface.co/black-forest-labs/FLUX.1-dev",
        runtime: "Stub diffusion pipeline",
        styleTags: ["general", "detailed", "balanced"],
        taskSupport: ["txt2img"],
        sizeGb: 23.8,
        recommendedResolution: "1024×1024",
        note: "Quality-oriented generalist for the starter image lineup.",
        availableLocally: false,
        estimatedGenerationSeconds: 7.4,
        lastModified: "2025-01-09T00:00:00Z",
      },
    ],
  },
  {
    id: "sd35-medium",
    name: "Stable Diffusion 3.5 Medium",
    provider: "Stability AI",
    headline: "Latest Stability model optimised for consumer hardware with MMDiT architecture.",
    summary: "Modern architecture with strong prompt adherence and detail at a manageable model size for local use.",
    updatedLabel: "Curated balanced pick",
    badges: ["MMDiT", "Balanced", "Modern"],
    defaultVariantId: "stabilityai/stable-diffusion-3.5-medium",
    variants: [
      {
        id: "stabilityai/stable-diffusion-3.5-medium",
        familyId: "sd35-medium",
        name: "Stable Diffusion 3.5 Medium",
        provider: "Stability AI",
        repo: "stabilityai/stable-diffusion-3.5-medium",
        link: "https://huggingface.co/stabilityai/stable-diffusion-3.5-medium",
        runtime: "Stub diffusion pipeline",
        styleTags: ["general", "detailed", "modern"],
        taskSupport: ["txt2img"],
        sizeGb: 11.9,
        recommendedResolution: "1024×1024",
        note: "Latest Stability offering targeting a good quality-to-resource balance.",
        availableLocally: false,
        estimatedGenerationSeconds: 5.8,
        lastModified: "2025-03-12T00:00:00Z",
      },
    ],
  },
  {
    id: "sd35-turbo",
    name: "Stable Diffusion 3.5 Large Turbo",
    provider: "Stability AI",
    headline: "Distilled large model for fast, high-quality generation in fewer inference steps.",
    summary: "Best pick when you want near-instant drafts at higher fidelity than older turbo models.",
    updatedLabel: "Curated speed pick",
    badges: ["Turbo", "Fast", "High quality"],
    defaultVariantId: "stabilityai/stable-diffusion-3.5-large-turbo",
    variants: [
      {
        id: "stabilityai/stable-diffusion-3.5-large-turbo",
        familyId: "sd35-turbo",
        name: "Stable Diffusion 3.5 Large Turbo",
        provider: "Stability AI",
        repo: "stabilityai/stable-diffusion-3.5-large-turbo",
        link: "https://huggingface.co/stabilityai/stable-diffusion-3.5-large-turbo",
        runtime: "Stub diffusion pipeline",
        styleTags: ["fast", "quality", "general"],
        taskSupport: ["txt2img"],
        sizeGb: 16.5,
        recommendedResolution: "1024×1024",
        note: "Fastest high-fidelity model in the curated set.",
        availableLocally: false,
        estimatedGenerationSeconds: 3.1,
        lastModified: "2025-02-20T00:00:00Z",
      },
    ],
  },
  {
    id: "sdxl-balanced",
    name: "SDXL Balanced",
    provider: "Stability AI",
    headline: "General-purpose SDXL model for reliable, high-quality everyday image generation.",
    summary: "Established baseline with wide ecosystem support, LoRA compatibility, and proven quality.",
    updatedLabel: "Curated classic",
    badges: ["Balanced", "General", "Detailed"],
    defaultVariantId: "stabilityai/stable-diffusion-xl-base-1.0",
    variants: [
      {
        id: "stabilityai/stable-diffusion-xl-base-1.0",
        familyId: "sdxl-balanced",
        name: "Stable Diffusion XL Base 1.0",
        provider: "Stability AI",
        repo: "stabilityai/stable-diffusion-xl-base-1.0",
        link: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        runtime: "Stub diffusion pipeline",
        styleTags: ["general", "detailed", "balanced"],
        taskSupport: ["txt2img"],
        sizeGb: 13.1,
        recommendedResolution: "1024×1024",
        note: "Widely adopted SDXL baseline with strong community and LoRA ecosystem.",
        availableLocally: false,
        estimatedGenerationSeconds: 7.4,
        lastModified: "2023-10-30T00:00:00Z",
      },
    ],
  },
];

export function createMockImageArtifact(
  payload: ImageGenerationPayload,
  modelName: string,
  index = 0,
): ImageOutputArtifact {
  const seedBase = payload.seed ?? stableImageHash(`${payload.modelId}:${payload.prompt}`);
  const seed = seedBase + index;
  const createdAt = new Date(Date.UTC(2026, 3, 9, 12, 0, Math.min(59, index * 7))).toISOString();
  return {
    artifactId: `mock-${stableImageHash(`${payload.modelId}:${payload.prompt}:${seed}:${index}`)}`,
    modelId: payload.modelId,
    modelName,
    prompt: payload.prompt,
    negativePrompt: payload.negativePrompt ?? "",
    width: payload.width,
    height: payload.height,
    steps: payload.steps,
    guidance: payload.guidance,
    seed,
    createdAt,
    durationSeconds: Number((1.8 + (payload.steps / 12) + index * 0.4).toFixed(1)),
    previewUrl: placeholderImageDataUrl(payload.prompt, modelName, payload.width, payload.height, seed),
    runtimeLabel: "Placeholder image engine",
  };
}

export const mockImageOutputs: ImageOutputArtifact[] = [];

export const mockWorkspace: WorkspaceData = {
  system: {
    platform: "Darwin",
    arch: "arm64",
    hardwareSummary: "Apple Silicon / 48 GB unified memory",
    backendLabel: "MLX + Native cache",
    appVersion: "0.2.0",
    mlxAvailable: true,
    mlxLmAvailable: true,
    totalMemoryGb: 48,
    availableMemoryGb: 31.2,
    usedMemoryGb: 16.8,
    swapUsedGb: 0.3,
    cpuUtilizationPercent: 18.4,
    gpuUtilizationPercent: null,
    spareHeadroomGb: 25.2,
    runningLlmProcesses: [
      { pid: 81341, name: "python3", memoryGb: 2.7, cpuPercent: 18.1 },
      { pid: 81387, name: "OpenClaw", memoryGb: 0.4, cpuPercent: 1.2 },
    ],
    uptimeMinutes: 6.4,
    availableCacheStrategies: [
      { id: "native", name: "Native f16", available: true, bitRange: null, defaultBits: null, supportsFp16Layers: false },
    ],
  },
  recommendation: {
    title: "Recommended target: 70B class @ Native f16",
    detail:
      "This dashboard forecast is relative to the recommended target profile for this machine, not a currently selected chat model.",
    targetModel: "70B class",
    cacheLabel: "Native f16",
    headroomPercent: 65,
  },
  featuredModels: [
    {
      id: "gemma-4",
      name: "Gemma 4",
      provider: "Google",
      headline: "New multimodal Gemma family for reasoning, coding, and on-device workflows.",
      summary: "Strong general-purpose family with compact edge variants and a larger A4B option for workstation-class use.",
      description:
        "Gemma 4 covers compact edge deployment through larger multimodal reasoning models. It is a good fit when you want a modern generalist with long context and strong coding support.",
      updatedLabel: "Updated 3 days ago",
      popularityLabel: "323k downloads",
      likesLabel: "58 likes",
      badges: ["Staff pick", "Vision", "Reasoning"],
      capabilities: ["reasoning", "vision", "coding", "multilingual"],
      defaultVariantId: "google/gemma-4-26B-A4B-it",
      variants: [
        {
          id: "google/gemma-4-E4B-it",
          familyId: "gemma-4",
          name: "Gemma 4 E4B Instruct",
          repo: "google/gemma-4-E4B-it",
          link: "https://huggingface.co/google/gemma-4-E4B-it",
          paramsB: 4.5,
          sizeGb: 5.4,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["vision", "reasoning", "tool-use"],
          note: "Compact Gemma 4 variant for laptops and small desktops.",
          contextWindow: "256K",
          estimatedMemoryGb: 9.2,
          estimatedCompressedMemoryGb: 6.3,
          availableLocally: true,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "google/gemma-4-12B-it",
          familyId: "gemma-4",
          name: "Gemma 4 12B Instruct",
          repo: "google/gemma-4-12B-it",
          link: "https://huggingface.co/google/gemma-4-12B-it",
          paramsB: 12,
          sizeGb: 14.8,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["vision", "reasoning", "coding"],
          note: "Higher quality Gemma 4 option for larger local rigs.",
          contextWindow: "256K",
          estimatedMemoryGb: 19.4,
          estimatedCompressedMemoryGb: 13.2,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "google/gemma-4-26B-A4B-it",
          familyId: "gemma-4",
          name: "Gemma 4 26B A4B Instruct",
          repo: "google/gemma-4-26B-A4B-it",
          link: "https://huggingface.co/google/gemma-4-26B-A4B-it",
          paramsB: 26,
          sizeGb: 28.1,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["vision", "reasoning", "coding", "agents"],
          note: "Large multimodal Gemma 4 variant for workstation-class setups.",
          contextWindow: "256K",
          estimatedMemoryGb: 34.8,
          estimatedCompressedMemoryGb: 23.7,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "mlx-community/gemma-4-26b-a4b-it-5bit",
          familyId: "gemma-4",
          name: "Gemma 4 26B A4B MLX 5-bit",
          repo: "mlx-community/gemma-4-26b-a4b-it-5bit",
          link: "https://huggingface.co/mlx-community/gemma-4-26b-a4b-it-5bit",
          paramsB: 26,
          sizeGb: 18.5,
          format: "MLX",
          quantization: "5-bit",
          capabilities: ["vision", "reasoning", "coding", "agents"],
          note: "Community MLX conversion of the instruct checkpoint, with a bundled chat template for ready-to-run desktop chat.",
          contextWindow: "256K",
          estimatedMemoryGb: 22.9,
          estimatedCompressedMemoryGb: 15.6,
          availableLocally: false,
          launchMode: "direct",
          backend: "mlx",
        },
      ],
      readme: [
        "Gemma 4 is built for reasoning, coding, and multimodal understanding.",
        "Small variants target local deployment; larger variants suit workstation-class hardware.",
        "Official transformer repos still route through conversion, while community MLX variants can run directly when available.",
      ],
    },
    {
      id: "qwen-3-5",
      name: "Qwen 3.5",
      provider: "Qwen",
      headline: "Hybrid reasoning family with long context and strong agent support.",
      summary: "Useful when you want modern reasoning and coding performance with a wide spread of model sizes.",
      description:
        "Qwen 3.5 spans compact and MoE-heavy variants with long context support. It fits well for agent-style workflows, tool use, and coding-heavy chats.",
      updatedLabel: "Updated this month",
      popularityLabel: "Featured family",
      likesLabel: "Qwen official",
      badges: ["Reasoning", "Coding", "Long context"],
      capabilities: ["reasoning", "coding", "tool-use", "vision"],
      defaultVariantId: "Qwen/Qwen3.5-9B",
      variants: [
        {
          id: "Qwen/Qwen3.5-4B",
          familyId: "qwen-3-5",
          name: "Qwen3.5 4B",
          repo: "Qwen/Qwen3.5-4B",
          link: "https://huggingface.co/Qwen/Qwen3.5-4B",
          paramsB: 4,
          sizeGb: 5.1,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["reasoning", "coding", "tool-use"],
          note: "Smaller Qwen 3.5 variant with strong utility for everyday local work.",
          contextWindow: "262K",
          estimatedMemoryGb: 8.7,
          estimatedCompressedMemoryGb: 5.9,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "Qwen/Qwen3.5-9B",
          familyId: "qwen-3-5",
          name: "Qwen3.5 9B",
          repo: "Qwen/Qwen3.5-9B",
          link: "https://huggingface.co/Qwen/Qwen3.5-9B",
          paramsB: 9,
          sizeGb: 10.9,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["reasoning", "coding", "vision", "video", "tool-use"],
          note: "Balanced Qwen 3.5 option for serious local chat, code, and agent tasks.",
          contextWindow: "262K",
          estimatedMemoryGb: 15.8,
          estimatedCompressedMemoryGb: 10.7,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "mlx-community/Qwen3.5-9B-4bit",
          familyId: "qwen-3-5",
          name: "Qwen3.5 9B MLX 4-bit",
          repo: "mlx-community/Qwen3.5-9B-4bit",
          link: "https://huggingface.co/mlx-community/Qwen3.5-9B-4bit",
          paramsB: 9,
          sizeGb: 6,
          format: "MLX",
          quantization: "4-bit",
          capabilities: ["reasoning", "coding", "vision", "video", "tool-use"],
          note: "Community MLX conversion for Apple Silicon with a much quicker local launch path.",
          contextWindow: "262K",
          estimatedMemoryGb: 10.8,
          estimatedCompressedMemoryGb: 7.3,
          availableLocally: false,
          launchMode: "direct",
          backend: "mlx",
        },
        {
          id: "lmstudio-community/Qwen3.5-9B-GGUF",
          familyId: "qwen-3-5",
          name: "Qwen3.5 9B GGUF",
          repo: "lmstudio-community/Qwen3.5-9B-GGUF",
          link: "https://huggingface.co/lmstudio-community/Qwen3.5-9B-GGUF",
          paramsB: 9,
          sizeGb: 5.8,
          format: "GGUF",
          quantization: "Q4_K_M",
          capabilities: ["reasoning", "coding", "tool-use"],
          note: "Community GGUF pack with ready-made quantizations for quick llama.cpp runs.",
          contextWindow: "262K",
          estimatedMemoryGb: 8.1,
          estimatedCompressedMemoryGb: 5.5,
          availableLocally: false,
          launchMode: "direct",
          backend: "llama.cpp",
        },
        {
          id: "Qwen/Qwen3.5-35B-A3B-FP8",
          familyId: "qwen-3-5",
          name: "Qwen3.5 35B A3B",
          repo: "Qwen/Qwen3.5-35B-A3B-FP8",
          link: "https://huggingface.co/Qwen/Qwen3.5-35B-A3B-FP8",
          paramsB: 35,
          sizeGb: 22.8,
          format: "Transformers",
          quantization: "FP8",
          capabilities: ["reasoning", "coding", "vision", "agents"],
          note: "Sparse MoE-style Qwen 3.5 variant tuned for high-end local or server workflows.",
          contextWindow: "262K",
          estimatedMemoryGb: 30.4,
          estimatedCompressedMemoryGb: 20.7,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
      ],
      readme: [
        "Qwen 3.5 is a reasoning-first family with long context and strong coding support.",
        "Thinking mode is model-native, so it works well for agent-style threads and tool-rich prompts.",
        "The catalog now mixes official transformer repos with community GGUF and MLX variants so you can go straight to a runnable format when one exists.",
      ],
    },
    {
      id: "nemotron-3-nano",
      name: "Nemotron 3 Nano",
      provider: "NVIDIA",
      headline: "Compact reasoning-first family aimed at efficient local deployment.",
      summary: "Good fit when you want a modern small model that still feels capable in chat and tool use.",
      description:
        "Nemotron 3 Nano focuses on local efficiency and reasoning utility. The GGUF variant is ready to use directly in the local llama.cpp path, while the BF16 weights can feed conversion workflows.",
      updatedLabel: "Updated 2 weeks ago",
      popularityLabel: "New release",
      likesLabel: "NVIDIA official",
      badges: ["Popular", "Reasoning", "Local-first"],
      capabilities: ["reasoning", "tool-use", "chat"],
      defaultVariantId: "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
      variants: [
        {
          id: "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
          familyId: "nemotron-3-nano",
          name: "Nemotron 3 Nano 4B GGUF",
          repo: "nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
          link: "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF",
          paramsB: 4,
          sizeGb: 3.1,
          format: "GGUF",
          quantization: "Q4_K_M",
          capabilities: ["reasoning", "chat", "tool-use"],
          note: "Direct-load GGUF path for fast local trials and thread switching.",
          contextWindow: "128K",
          estimatedMemoryGb: 6.4,
          estimatedCompressedMemoryGb: 4.4,
          availableLocally: true,
          launchMode: "direct",
          backend: "llama.cpp",
        },
        {
          id: "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
          familyId: "nemotron-3-nano",
          name: "Nemotron 3 Nano 4B BF16",
          repo: "nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
          link: "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-BF16",
          paramsB: 4,
          sizeGb: 8.2,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["reasoning", "chat", "tool-use"],
          note: "Official BF16 weights if you want to convert into an MLX-friendly local artifact.",
          contextWindow: "128K",
          estimatedMemoryGb: 8.9,
          estimatedCompressedMemoryGb: 6,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
          familyId: "nemotron-3-nano",
          name: "Nemotron 3 Nano 30B A3B FP8",
          repo: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
          link: "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
          paramsB: 30,
          sizeGb: 35,
          format: "Transformers",
          quantization: "FP8",
          capabilities: ["reasoning", "thinking", "tool-use", "coding", "agents"],
          note: "Larger official Nemotron 3 Nano checkpoint with configurable reasoning traces and very long context.",
          contextWindow: "1M",
          estimatedMemoryGb: 26.2,
          estimatedCompressedMemoryGb: 17.8,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
        {
          id: "lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
          familyId: "nemotron-3-nano",
          name: "Nemotron 3 Nano 30B A3B GGUF",
          repo: "lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
          link: "https://huggingface.co/lmstudio-community/NVIDIA-Nemotron-3-Nano-30B-A3B-GGUF",
          paramsB: 30,
          sizeGb: 24.5,
          format: "GGUF",
          quantization: "Q4_K_M",
          capabilities: ["reasoning", "thinking", "tool-use", "coding", "agents"],
          note: "Community GGUF conversion for the larger Nemotron 3 Nano release when you want a ready llama.cpp path.",
          contextWindow: "1M",
          estimatedMemoryGb: 23.2,
          estimatedCompressedMemoryGb: 15.8,
          availableLocally: false,
          launchMode: "direct",
          backend: "llama.cpp",
        },
      ],
      readme: [
        "Nemotron 3 Nano is built for compact local deployments without falling back to obviously weak outputs.",
        "The family now includes both the smaller 4B checkpoints and the newer 30B A3B release.",
        "Official checkpoints remain available for conversion, while community GGUF packs give you a direct runtime path.",
      ],
    },
    {
      id: "devstral-small",
      name: "Devstral Small",
      provider: "Mistral AI",
      headline: "Agentic coding model family tuned for software engineering tasks.",
      summary: "Best when the conversation is code-heavy and you want a thread-specific model for repo work.",
      description:
        "Devstral focuses on software engineering workflows and tool-using assistants. The GGUF release is directly usable, and the BF16 release can feed conversion-oriented setups.",
      updatedLabel: "Updated 3 weeks ago",
      popularityLabel: "Trending with coding users",
      likesLabel: "Mistral official",
      badges: ["Coding", "Agents", "Tool use"],
      capabilities: ["coding", "agents", "tool-use"],
      defaultVariantId: "mistralai/Devstral-Small-2507_gguf",
      variants: [
        {
          id: "mistralai/Devstral-Small-2507_gguf",
          familyId: "devstral-small",
          name: "Devstral Small 2507 GGUF",
          repo: "mistralai/Devstral-Small-2507_gguf",
          link: "https://huggingface.co/mistralai/Devstral-Small-2507_gguf",
          paramsB: 24,
          sizeGb: 15.7,
          format: "GGUF",
          quantization: "Q4_K_M",
          capabilities: ["coding", "agents", "tool-use"],
          note: "Direct GGUF path for local coding threads and repo-centric workflows.",
          contextWindow: "128K",
          estimatedMemoryGb: 18.8,
          estimatedCompressedMemoryGb: 12.8,
          availableLocally: false,
          launchMode: "direct",
          backend: "llama.cpp",
        },
        {
          id: "mistralai/Devstral-Small-2507",
          familyId: "devstral-small",
          name: "Devstral Small 2507 BF16",
          repo: "mistralai/Devstral-Small-2507",
          link: "https://huggingface.co/mistralai/Devstral-Small-2507",
          paramsB: 24,
          sizeGb: 29.4,
          format: "Transformers",
          quantization: "BF16",
          capabilities: ["coding", "agents", "tool-use"],
          note: "Official BF16 weights for conversion-oriented local setups.",
          contextWindow: "128K",
          estimatedMemoryGb: 31.5,
          estimatedCompressedMemoryGb: 21.4,
          availableLocally: false,
          launchMode: "convert",
          backend: "mlx",
        },
      ],
      readme: [
        "Devstral is tuned for software engineering and tool-using workflows.",
        "Use the GGUF variant when you want the quickest path into local code threads.",
        "Use the BF16 repo when you want to convert into an MLX artifact instead of running GGUF.",
      ],
    },
  ],
  library: [],
  settings: {
    modelDirectories: [
      {
        id: "hf-cache",
        label: "Hugging Face cache",
        path: "~/.cache/huggingface/hub",
        enabled: true,
        source: "default",
        exists: false,
        modelCount: 0,
      },
      {
        id: "mlx-cache",
        label: "MLX cache",
        path: "~/.cache/mlx",
        enabled: true,
        source: "default",
        exists: false,
        modelCount: 0,
      },
      {
        id: "home-models",
        label: "Models",
        path: "~/Models",
        enabled: true,
        source: "default",
        exists: false,
        modelCount: 0,
      },
    ],
    preferredServerPort: 8876,
    allowRemoteConnections: false,
    requireApiAuth: true,
    autoStartServer: false,
    launchPreferences: {
      contextTokens: 8192,
      maxTokens: 512,
      temperature: 0.7,
      cacheBits: 0,
      fp16Layers: 4,
      fusedAttention: false,
      cacheStrategy: "native",
      fitModelInMemory: true,
      speculativeDecoding: false,
      treeBudget: 0,
    },
  },
  chatSessions: [],
  runtime: {
    state: "idle",
    engine: "preview",
    engineLabel: "No backend",
    loadedModel: null,
    supportsGeneration: false,
    serverReady: false,
    activeRequests: 0,
    requestsServed: 0,
    runtimeNote: "Backend is offline. Start the backend service to load and run models.",
    nativeBackends: {
      pythonExecutable: "python",
      mlxAvailable: false,
      mlxLmAvailable: false,
      mlxUsable: false,
      mlxVersion: null,
      mlxLmVersion: null,
      mlxMessage: "Preview workspace only. Start the backend service to inspect local runtimes.",
      ggufAvailable: false,
      llamaCliPath: null,
      llamaServerPath: null,
      converterAvailable: false,
    },
  },
  server: {
    status: "idle",
    baseUrl: "http://127.0.0.1:8876/v1",
    localhostUrl: "http://127.0.0.1:8876/v1",
    lanUrls: [],
    bindHost: "127.0.0.1",
    remoteAccessActive: false,
    port: 8876,
    activeConnections: 0,
    concurrentRequests: 0,
    requestsServed: 0,
    loadedModelName: null,
    loading: null,
    logTail: [
      "Backend is offline in preview mode.",
      "Desktop builds use the live sidecar instead of this mock workspace.",
      "Start the backend service to inspect real local models and chats.",
    ],
  },
  benchmarks: [],
  logs: [],
  activity: [],
  preview: {
    bits: 3,
    fp16Layers: 4,
    numLayers: 32,
    numHeads: 32,
    hiddenSize: 4096,
    contextTokens: 8192,
    paramsB: 7,
    baselineCacheGb: 4,
    optimizedCacheGb: 1.8,
    compressionRatio: 2.3,
    estimatedTokS: 30.7,
    speedRatio: 0.59,
    qualityPercent: 97.6,
    diskSizeGb: 4.3,
    summary:
      "Native f16 cache provides full-precision KV storage. Install optional compression strategies for reduced memory usage on larger models.",
  },
  quickActions: ["Online Models", "New Thread", "Start Server", "Convert to MLX", "Open Logs"],
};
